### PR TITLE
Implant Hotfix

### PR DESCRIPTION
**Pull request by xxalpha**
Removed Reviver implant and commented out Nutriment implant designs so they can't be printed.

Fixes https://github.com/tgstation/-tg-station/issues/8796
Fixes https://github.com/tgstation/-tg-station/issues/8791

This is a hotfix and is the most I can do right now. I'll look into fixing the protolathe bug in a day or two.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Just a note, the bug with the nutriment implant actually exists for the revive one, but nobody noticed because we changed its req_tech to 10 for all 3 categories.

Its because you don't actually list what to spawn, like with the other ones. minor mistake.

**Comment by Amnestik** [comment]
You could just nerf the reviver implant instead of removing it.

**Comment by Jalleo** [comment]
@Amnestik read the content it will be sorted later on.

**Comment by Amnestik** [comment]
He's going to fix the bug with the nutriment implant, not the reviver implant.

**Comment by xxalpha** [comment]
I'll probably reimplement the Reviver implant, I can't think straight right now and people are reporting inconsistencies and bugs and it being OP (it is) and I'd rather just take it out for now.

**Pull request merged**
