### PR TITLE
wastes a get

### PR DESCRIPTION
**Pull request by hornygranny**
wastes a get

### CODE REVIEW

**Comment by Incoming5643** [comment]
:+1:

**Comment by Anonus** [comment]
not actually a meme pr BUT STILL A MEME GODDAMN

**Comment by Xhuis** [comment]
@Aranclanos 
DUNKED
U
N
K
E
D

**Comment by Aloraydrel** [comment]
the absolute madman

**Comment by ExcessiveUseOfCobblestone** [comment]
I blame goof for this

**Comment by duncathan** [comment]
I looked at the changes and I have yet to stop laughing :+1:

**Comment by PKPenguin321** [comment]
:+1: removes aranclanos

**Comment by Razharas** [comment]
Hg is trying to regain headcoder i see

**Pull request merged**
