### PR TITLE
Fixes french invasion.

### PR DESCRIPTION
**Pull request by xxalpha**
This has been bothering me for a long time.

### CODE REVIEW

**Comment by ike709** [comment]
:us: :us: :us: :us: :us:

**Comment by RemieRichards** [comment]
:gb: :gb: :gb: :gb: :gb:

**Comment by Incoming5643** [comment]
That's all you can say!

**Comment by Miauw62** [comment]
tfw no belgium flag
this will have to do
:beers: :beers: :beers: :beers: :beers: :beers: :beers:

**Pull request merged**
