### PR TITLE
Detective can be a traitor/double agent.

### PR DESCRIPTION
**Pull request by xxalpha**
_Corgi carcass in maintenance this morning, tire tread on burst stomach._
_This station is afraid of me. I have seen its true face._
_The hallways are extended disposals and the disposals are full of blood and when the drains finally scab over all the vermin will drown._
_The accumulated filth of all their ERP and murderboner will foam up about their waists and all the stuttering whores and heads of staff will look up and shout "save us"..._
_And I'll look down and whisper "No"._

_Stood in starlight, sweltering blood stains on chest like map of violent new continent._
_Felt cleansed, felt dark station turn under my feet and knew what cats know that makes them scream like babies in the night._
_Looked at space through windows layered with human fat and God was not there._
_The cold, suffocating dark goes on forever and we are alone._
_This rudderless universe is not shaped by vague metaphysical forces._
_It is not God who kills the puppies, not fate that butchers them or destiny that feeds them to the carps._
_It's us._
_Only us..._

:cl:
rscadd: Detective can be a Traitor/Double Agent.
tweak: Removed Detective's access to security lockers and secbots.
tweak: Removed bowman's headset from Detective's locker.
tweak: Box Brig Security Office and Locker Room require a higher access level (Security Officer level).
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
You would need to remove his loyalty implant as well.

**Comment by xxalpha** [comment]
Loyalty implant only prevents cult and revolution, that's not the purpose of this PR. Just Traitor and DA, which is a subtype of Traitor.

**Comment by Zilenan91** [comment]
Gonna give a big :-1: 

Detectives are just gonna murder all of security with their OP revolver every round and then go on to murder everybody else.

**Comment by KazeEspada** [comment]
The lawyer can also murder all of security with a revolver. He just pays a few extra TC.

**Comment by tkdrg** [comment]
This will just lead to sec being shitlers against the det because 'omg what if he was antag!!' which would be awful. Also the issue of spawning with the best weapon on the station which is kinda BS either way but still.

**Comment by MMMiracles** [comment]
I need my loose cannon detectives who get the job done by any means necessary.

:+1:

**Comment by GunHog** [comment]
All-or-nothing in my opinion, or remove his loyalty implant. It is a _consistency_ issue otherwise. Alternatively, you could enable the Traitor Security config option.

**Comment by Metacide** [comment]
Security's in a good place at the moment, traitorsec would shit that all up again. 

Please no. :-1:

**Comment by xxalpha** [comment]
Detective should not be a shitcurity officer in a trenchcoat.

**Comment by bgobandit** [comment]
:+1: x infinity

**Comment by TheNightingale** [comment]
I like the idea of a loose cannon Det, but can we really trust the players not to abuse antag status and a .38? Traitor HoP gets abused all the time, and traitor Det would be similar, I'd expect.

**Comment by Zilenan91** [comment]
Actually yeah this is literally traitorsec lite.

It's just gonna mean that the detective can't ever arrest people or else people are going to scream, [Common] Urist says, "HELP DETECTIVE TRAITOR HE'S KILLING ME"

**Comment by xxalpha** [comment]
I think that is a problem with players who will do anything to "win" and really shouldn't be allowed. You already can't cry wolf with cyborgs. If the detective is taking you into maintenance instead of the brig, then sure go ahead and scream for help.

**Comment by bgobandit** [comment]
>It's just gonna mean that the detective can't ever arrest people 

As it should be. The detective isn't supposed to be arresting people in the first place.

**Comment by xxalpha** [comment]
That too, you don't _have_ to make arrests as detective, from an IC perspective. Report crimes and add them to the records and let SOs and beepsky take care of them.

**Comment by TrustyGun** [comment]
They typically do arrest people however, because of their loose cannon status.

**Comment by Zilenan91** [comment]
With how sec is on this server, you're usually the only one on it if you go detective, so you HAVE to arrest people. A fully staffed security department just doesn't happen.

**Comment by PKPenguin321** [comment]
:+1:

**Comment by MMMiracles** [comment]
People seem to forget that the big issue with traitorsec was that it was essentially spawning in an antag into a job with some level of authority, multiple reliable stuns, restraining abilities, and access to multiple areas that were rarely accessed and deadzones when it came to camera coverage.

Detective has a gun that takes over 7 bullets to actually crit, requires physical ammo that can only be obtained from a 'lathe, a free pair of sunglasses, mediocre armor, and as much brig access as the lawyer (who can also be a traitor).

**Comment by PKPenguin321** [comment]
You just described the HoP, only he has better access and a worse gun and can already be a traitor.

**Comment by optimumtact** [comment]
the advanced egun is better than the det's revolver though?

**Comment by PKPenguin321** [comment]
Sorta
It a few more hits to stun, can't beat riot shields as consistently, and can't be speedloaded, but otherwise its better than the revolver ammo capacity and damage wise

**Comment by Zilenan91** [comment]
HoP antag is already terrible though, it's just all access, subvert the AI, and kill everyone. Detective is going to be the same thing except it's traitorsec and that's going to be awful because nobody will ever trust the detective to do anything.

**Comment by MMMiracles** [comment]
@Zilenan91 Man I literally just said why it isn't like traitorsec.

That also implies people trust the detective to begin with.

**Comment by Fox-McCloud** [comment]
:-1: 

If he's going to be a traitor, he shouldn't have a loyalty implant---loyalties don't just prevent conversion--they *imply* trustworthiness and also make beepsky not want to go after you butt as much.

Also, it would be super easy to dominate the field as tator-tot detective.

**Comment by xxalpha** [comment]
They don't imply trustworthyness. A traitor can be implanted at any time.

**Comment by Shapsy** [comment]
Literally all the jobs that start with loyalty implants at roundstart are immune to antag, and only them, that's not a coincidence 

Furthermore .38 is piss easy to get on box by just giving cargo some metal and printing out like 5 speedloaders, and you can just skip that step on meta by using the public autolathe. Furthermore, the fact that it's a six shot taser without the range limit that can be reloaded instantly via a tiny item and deals brute damage means it's a pretty damn good gun, I don't get why people think it sucks

**Comment by Dorsisdwarf** [comment]
Also loyalty implants = non-traitor is a server config setting.

**Comment by xxalpha** [comment]
Why is that a config when the gamecode can handle that?

**Comment by xxalpha** [comment]
@Shapsy you can make that argument for a loyal detective as well. It's not my fault detective was buffed like that.

**Comment by bgobandit** [comment]
we should just remove loyalty implants tbh

**Comment by bgobandit** [comment]
also

>Call it a perk of the job. Chemists have poisons, scientists have bombs, engineers have the singulo, detective has a gun.

scientists, cargonians, lawyers can all easily get guns with an emag, not to mention traitors can order the revolver which kicks the ass of all those other guns, I don't get why "has a gun!!!" is an argument at all

**Comment by Anonmare** [comment]
Remove loyalty implant, the spare speedloaders, access to security gear lockers, bowman headset/secHUD and Detective traitor might be viable. Maybe require the det's gun to be cocked after use like the riot shotgun to make it a less-than-reliable method of stunning someone.

**Comment by xxalpha** [comment]
>Maybe require the det's gun to be cocked after use like the riot shotgun to make it a less-than-reliable method of stunning someone.

Absolutely not.

But I'll change the access.

**Comment by tkdrg** [comment]
The detective's revolver really does need a nerf though, regardless of this PR.

**Comment by xxalpha** [comment]
Another PR can nerf it, but the use-to-reload mechanic is shit. It's why I changed the kinetic accelerator.

**Comment by Aloraydrel** [comment]
Ignore the babies and JUST DO IT

**Comment by Zilenan91** [comment]
I kinda like this if I'm honest. Though don't nerf the detective revolver. His revolver is sacred.

**Comment by TheNightingale** [comment]
"Remove loyalty implant": Ehh, okay.
"the spare speedloaders": Nope.
"access to security gear lockers": Det only gets these on lowpop anyway.
"bowman headset/secHUD": The bowman's is so they don't get flashbanged; the HUD is on lowpop.
 "Detective traitor might be viable. Maybe require the det's gun to be cocked after use like the riot shotgun to make it a less-than-reliable method of stunning someone": It's _supposed_ to be a reliable method of stunning someone. The Detective gets a great weapon, but rarely has to use it.

**Comment by Anonmare** [comment]
Detective shouldn't be using flashbangs if we're lowering him to more a PI than a police detective. They're GGnore for an entire room in LoS and they can still get apretty easy access to a bowmanset from the warden/HoS/Any Sec Officer. 
The only way we can make antag detective work is by making them less on par with a security officer but still in a somewhat trusted position

**Comment by xxalpha** [comment]
Honestly I think bowmans should just be deleted from the code.

In any case, I removed that filth from the detective's locker.

**Comment by Zilenan91** [comment]
Nah, antag detective can work by making them completely separate from Security. An impartial judge who can help them in their time of need, not having brig access and maybe not even having a security headset but that's probably too far. Not what he is now which is basically a sec officer 2.0 because of his gun.

**Comment by TheNightingale** [comment]
Putting Detective above Lawyer on trustworthiness might work - Brig access (Security/Holding Cells on lowpop), Security headset, but also a cool gun.

Remember, changing the Detective's stuff affects non-antag Detectives too; you're trying to code it so antag Dets are balanced, when really, they don't need to be. They just need to know not to kill everyone with the .38. Detectives are fine gameplay-wise at the moment - we know some antag Dets will abuse their position, but why change the Detective when we can change the abuse?

Here's an idea: Detectives, if they roll traitor, don't get normal objectives or an uplink - they get...
"You are a loose cannon. You'll do whatever it takes to uncover the truth - but be careful not to become that which you hunt. You still obey the law, and cold-blooded murder isn't in your nature, but like all good Detectives, you play fast and loose with the rules; in the pursuit of justice, let nothing get in your way."
A free pass to use more force than usually necessary, but they don't get licence-to-kill on innocents.

**Comment by xxalpha** [comment]
The only thing they lose here is security officer level access and bowmans.

**Comment by bgobandit** [comment]
>"You are a loose cannon. You'll do whatever it takes to uncover the truth - but be careful not to become that which you hunt. You still obey the law, and cold-blooded murder isn't in your nature, but like all good Detectives, you play fast and loose with the rules; in the pursuit of justice, let nothing get in your way."

actually I like this idea, it'd require hella enforcement from admins though, see people using "survivor" as an excuse to murderbone with no regard for their own life

**Comment by TheNightingale** [comment]
Access_weapons is having a weapon permit. Do you really want Beepsky to attack the Detective for having a gun they're authorised to use?
Lowpop ("minimal_access") Dets also still need Sec access, since in lowpop, there probably won't be anyone else in Security anyway.

We could add similar flavour text to survivors - "You only care about survival. Ensure that you have as many guns as you can hold, but risking your life for more doesn't strike you as a good idea - you only want to get through this day alive, and needless killing will draw unwanted attention to you."

**Comment by Zilenan91** [comment]
I don't think this change really even makes the detective a part of security anymore.

**Comment by xxalpha** [comment]
@TheNightingale fixed that

**Comment by TheNightingale** [comment]
Can you give them the lowpop Sec lockers back too? On highpop, the real Security Officers can do the work, but when the Detective is the only one on the team, they're going to need to follow up on arrest warrants with HUDSunglasses, flashbang people with bowman's and flashbangs, and do actual melee combat with a stunbaton.

**Comment by Zilenan91** [comment]
There's like three detective prs up right now, let's see what happens with those before we start thinking ahead.

**Comment by xxalpha** [comment]
That just means that, if they are traitors, they can just waltz in there and space security equipment or arm themselves even better for free.

The separation between the investigation department and security is absolute.

**Comment by TheNightingale** [comment]
Lowpop antag Dets won't need Security gear, since they can just kill things (unless they're loose-cannons - "find the truth, no matter what"). How about if they lose the locker access on lowpop, but get HUDShades by default (on spawn) and keep the bowman's? They can follow up on arrests, but they'll need someone else to give them the SO gear like the stunbaton/flashbang/pepperspray.

Also, as a frequent Detective player, I'm concerned and somewhat excited about all these changes...

**Comment by xxalpha** [comment]
I think it is fair to allow actual Security to control what equipment the detective gets besides his starting stuff, since he is a potential traitor to NT, even in lowpop.

**Comment by KorPhaeron** [comment]
Players have repeatedly expressed a distaste for traitor security.

Players have repeatedly expressed a distaste for any sort of rule restrictions on antagonist actions.

I think pseudo traitor sec will probably just use his free gun to murder a ton of people, or trigger those old style riots that happened whenever someone got arrested.

Something other than a full antag with different objectives might be cool though?

To be clear I miss traitor sec, I just believe the server has no stomach for it

**Comment by Zilenan91** [comment]
This pr removes almost all of his brig access though, so he shouldn't and can't arrest people, just investigate things and chill in the bar now that he's not security anymore.

**Comment by KorPhaeron** [comment]
I promise you that someone with a gun/baton/cuffs/sec headset will still arrest people.

**Comment by Zilenan91** [comment]
Then take away his baton cuffs and sec headset

**Comment by xxalpha** [comment]
There are some mapping problems related to this, which I should fix. The Security Office airlock uses front door access and it shouldn't. I should probably also remove permabrig access from the detective.

The point of this PR is to undo the bullshit that was done to the detective. The detective shouldn't be just another Security Officer slot, it should be its own role and serve its own purpose. By giving a detective traitor freedom, he can fill the niche of traitor sec without causing major distrust among security personnel.

I am for loyal sec, but the detective should be its own element in the Security department and not that security officer with extra shit and his own private office.

**Comment by Zilenan91** [comment]
This combined with the other two detective prs seem like they'll make a real nice role to play.

**Comment by Czarcastic** [comment]
What if he didn't have an antag chance, per say, but a small chance to gain a status like loose cannon or something?

That way security wouldn't have any reason to distrust the detective because muh valids

**Comment by PKPenguin321** [comment]
the half-antag loose cannon idea is kind of bad since it encourages validhunting more than anything else

**Comment by xxalpha** [comment]
Agreed, let the player do as he will with his antag status.

**Comment by AdamElTablawy** [comment]
I am for this.

Again, the detective's gun is powerful, but you don't see antags grabbing the det's gun and becoming unkillable murder machines, because a traitor fully kitted up in all of the detective's gear can still be stopped.

Detective shouldn't be arresting people ANYWAY, but he does, because he's a loose cannon. People screaming DET TRAITOR for a legit arrest is going to be handled the same was as screaming BORG ROGUE for a security cyborg arresting you for beating a braindead with a fire extinguisher.

It's going to be refreshing to see more subversive elements in the security area. And without SecHUD's or Bowman or a loyalty implant, the detective is going to be at a disadvantage prior to what he was at before.

There is, however, a minor issues with this.

Without a loyalty implant, this can lead to revs converting the detective, gangs converting the detective, or in an absolute worst case scenario, a REVHEAD DETECTIVE.

**Comment by xxalpha** [comment]
Yes well, I had to remove the implant or this wouldn't work because muh configs.

I trust the inner powergamer of security players to implant the detective every round, though.

**Comment by AdamElTablawy** [comment]
REVHEAD

DETECTIVES.

**Comment by xxalpha** [comment]
They will make the station great again.

**Comment by AdamElTablawy** [comment]
GANGHEAD DETECTIVES.

CULTIST DETECTIVES. 

i'm all for traitor dets and stuff but the detective running into sec with 3 assistants and gunning down all of sec in quick succession is not good

**Comment by Zilenan91** [comment]
Then just remove their basic brig access and the problem is solved.

**Comment by xxalpha** [comment]
Actually only Traitor/DA don't have Detective in their protected roles.

The detective can't be a rev head or anything else, unless converted, just traitor/DA.

**Comment by AdamElTablawy** [comment]
Oh thank god.

**Comment by Dorsisdwarf** [comment]
If you want the det to be more of a PI, why not make the HOP his head?

**Comment by Thunder12345** [comment]
:-1: Traitor sec was removed for a reason, bringing it back it just gonna cause trust issues.

**Comment by KazeEspada** [comment]
Its the detective not officers. Hes the sleeze ball of sec.

ALSO DONT REMOVE BRIG ACCESS, HE NEEDS IT TO INTERROGATE PEOPLE.

Besides lawyers have brig access.

**Comment by TheNightingale** [comment]
Making the Security Office access_security is pointless; it doesn't have anything worth upgrading the access for, and at the moment, it lets Lawyers and the Detective shoot the breeze with off-duty Officers.

**Comment by Steelpoint** [comment]
I have enough trouble's dealing with Traitor Lawyers, this change will not leave a positive impact for Detective's and Security in general.

Detective's will find it very hard to work with Security, at best they'll always be suspected of malicious intent. At worst the Detective will be first on the stun and arrest list.

Security will have it even worse as the small boost to having a Detective with forensics skill's goes out the reliability window. Detective's already detest the HoS taking their spare forensics scanner to invalidate their job, this change will simply demand HoS's take the spare scanner so as to not leave any doubt.

**Comment by PKPenguin321** [comment]
>I have enough trouble's dealing with Traitor Lawyers

Have you considered gitting gud?

**Comment by LanCartwright** [comment]
Regarding this, I'd rather see more of a traitor detective having to follow more guidelines than the traditional murderbone traitor. I.E. enforce some kind of guideline and different formatting.

**Comment by xxalpha** [comment]
If you follow the law you don't have to worry.

**Comment by ExcessiveUseOfCobblestone** [comment]
I like detective pls buff

also the gun argument is valid because it's a F R E E gun unlike the revolver that costs 13 TCs. Enjoy your holoparasite Dets turbo-murderbone.

Also Enjoy the HoS giving security the det scanner since he can trust them more than he can trust the Det so you basically have 2 Dets: One for Sec and one that MAY BE pro-sec.

:-1:

**Comment by xxalpha** [comment]
>I like detective pls buff

Go suck a dick.

**Comment by as334** [comment]
:-1: Nobody will ever trust the detective again. Sec will think that anyone he finds for crimes is just their target, and crew members will never collaborate with investigations due to fear of being type-killed. Would effectively ruin detectives non-antag job just so we can have shitty traitor-sec lite, and a traitor with access to more equipment

**Comment by PKPenguin321** [comment]
People will trust him the second the round is confirmed to not be traitor though, which is like 50% of rounds

**Comment by Zilenan91** [comment]
Also he's a loose cannon you aren't supposed to immediately trust the crazy noir man with a gun. 

This pr basically removes him from security and turns him into more of a private detective rather than a security detective.

**Comment by xxalpha** [comment]
In any round you trust who you want to trust. If you play SS13 expecting everyone to be out to murder you then how do you even have fun? Stop trying so hard to win and relax, dying is part of any job on this game.

**Comment by Durkel** [comment]
I'd say either go full security antag or not at all. This pr is just going to make everyone ignore the detective and the HoS will just take the scanner and do the work himself. If you really want to do something like this I'd suggest axing his implant, moving his office, removing his gun and making it a civilian job under PI.

**Comment by Czarcastic** [comment]
Making him a PI isn't a bad idea but he absolutely must keep his gun. What kind of detective doesn't have a gun?

**Comment by Cheimon** [comment]
:-1:

The detective has the best gun in the game (at round start, anyway) and is a core part of security.  Doing this is just making security less trustworthy as a whole, and is also going to see security being less keen to work with him on forensics.  The detective gets to be enough of a loose cannon already, you don't need to make him a nightmare to work with (for both security and the crew at large) to have Dirty Harry type policing.  I know I've certainly played a little looser as detective and been fine with it, killing multiple people if I want because the HOS is more lenient towards detective's role.

Expect to see detectives who fall under even a small amount of suspicion arrested, have all their weapons confiscated, and have one of their scanners turned over to someone like the HOS.  He is only permitted to be dangerous right now because security trusts him in the end, and you are taking that away.

**Comment by Steelpoint** [comment]
Detective antag will only work if you have security antag.

**Comment by duncathan** [comment]
Why the 70k changes to box?

**Comment by KorPhaeron** [comment]
I'm actually more worried about the detective being a convertable target than I am about him being traitor. I'll merge this if he gets his loyalty implant back.

**Comment by Zilenan91** [comment]
Yeah the detective would shit on people if he ever got revved.

**Comment by Steelpoint** [comment]
This is still a horrible change.

**Comment by Zilenan91** [comment]
It would've been a cool change if the .357 det revolver pr didn't get closed but now it kinda sucks.

**Comment by GunHog** [comment]
Having a loyalty implant and being able to be a traitor is a consistency issue. Why is ONLY the Det able to have a Loyalty implant AND be a traitor at the same time, but not the rest of Sec?

**Comment by xxalpha** [comment]
Traitors can be loyalty implanted.

**Comment by GunHog** [comment]
Yet roundstart loyalty-implanted personnel cannot be traitors unless the config is enabled. This one ignores the config, does it not?

**Comment by xxalpha** [comment]
The only config is to enable the use of protected_roles list.

**Comment by PKPenguin321** [comment]
woah

**Comment by Dorsisdwarf** [comment]
Habbeding

**Comment by Metacide** [comment]
This was a shitty idea from the start. Traitorsec was awful and that is what this is. :-1:

**Comment by Steelpoint** [comment]
People will start to dislike this change when suddenly no one in security or command ever trusts the detective ever again.

I'm also going to guess HoS's taking the spare scanner rates are going to sky rocket.

**Comment by KorPhaeron** [comment]
If it's awful it can be reverted. I am not attached to this change and was unsure of it being a good idea in the first place.

**Comment by Zilenan91** [comment]
I think it's a good idea because it takes the detective out of security and makes him into his own thing. We should even give him a regular or Service radio headset at this point tbh.

**Comment by KorPhaeron** [comment]
Why the hell would he need to talk to the chef?

**Comment by Zilenan91** [comment]
I couldn't think of a more applicable headset he would use that wouldn't be command.

**Comment by Steelpoint** [comment]
If you want a non-sec version then propose a civilian private investigator, instead of taking away a very useful role from security.

**Comment by xxalpha** [comment]
There will be no private investigator, detective is part of the security personnel.

**Pull request merged**
