### PR TITLE
[WIP] emp card/emag nerf

### PR DESCRIPTION
**Pull request by hornygranny**
new item to take some functionality away from the emag, and make the emag more of a hacking tool

### CODE REVIEW

**Comment by Cheridan** [comment]
:-1: Emag doesn't need nerfed.

Yes, it's a versatile tool with lots of potential uses. But nobody uses it for every single thing it's capable of doing. If you're a roboticist you'll get it to hack a cyborg, if you're a librarian you'll get it to open airlocks, if you're a cargo tech you'll get it to order black ops crates, etc and maybe a couple other things. It's like a swiss army knife: Yeah you got a corkscrew and a nail file on there too but how often do you need a corkscrew?

The only bad gameplay aspect of the emag is spreemagging where you just run around opening all the doors on the station just to be annoying, which can be solved with a cooldown or something.

**Comment by Amemelius** [comment]
> Item fine at current pricepoint for years.
> Utility item with no combat function, any higher cost and it means any traitor eschews precious combat equipment instead of choosing it as your major utility item
> Hue let's split it into two items that probably will cost much more than it was.

Awful ideas for $2000, Alex.

**Comment by Bawhoppen** [comment]
This has been incoming for years and I don't like it
Make the emag cost more but its better to keep it as one item for simplicity sake

**Comment by LanCartwright** [comment]
I for one support this

**Comment by Bawhoppen** [comment]
HG was ahead of his time and I should never have doubted his wisdom

**Pull request closed without merging**
