### PR TITLE
Revert "Smooth out gliding so movement isn't (as) jerky"

### LINKED ISSUE #11466: Dragging items under the new movement is fucking disgusting
Normal pull: Watch what you are dragging bounce around like a fucking toddler and hump the floor, especially bad if it is a piece of heavy machinery

Grab-pull: OH GOD THE HORROR, I cannot describe it except it just. looks. FUCKING. AWFUL

### PR DESCRIPTION
**Pull request by hornygranny**
Reverts tgstation/-tg-station#11159
game is not playable

Fixes #11466

### CODE REVIEW

**Comment by Anonus** [comment]
Rename this to "smooths out gliding so movement isn't as jerky" because it's totally accurate

**Comment by daman997** [comment]
D O   I T  :+1:

**Comment by WJohn** [comment]
Fixes #11466

**Comment by Aliannera** [comment]
JUST D O I T.

**Comment by Dorsisdwarf** [comment]
Retroactive justification is the best justification

**Comment by Aranclanos** [comment]
I was away the whole day, can I get some info on what happened

**Comment by Anonus** [comment]
the thing got merged, but it was intended to work on only multiples of 10 fps and fps got set to 16, which caused jerkyness.
the fact that it only worked right on multiples of 10 wasn't known until after it got reverted.

**Comment by Steelpoint** [comment]
So can we revert the revert of the feature?

**Pull request merged**
