### PR TITLE
fixes critical priority bug

### LINKED ISSUE #8681: Nashville Tennessee (Space Carp Typo)
nashville tennesse
It should be "gnashes."

Fuck.

How does something go this long without being noticed? Is everyone just secretly illiterate?
Is it some kind of dank meme I'm not ebin enough to understand yet?

### PR DESCRIPTION
**Pull request by dannno**
jesus christ think of all those g's. jesus fucking christ. what have we done
fixes #8681

### CODE REVIEW

**Comment by hornygranny** [comment]
AHHHHH

**Comment by dannno** [comment]
i only pray that we are able to make up for all we've lost.

**Comment by buttsmcgee** [comment]
People should remember this when they're thinking about which server to choose.

We're now the only one with full g retention.

**Comment by Antimattercarp** [comment]
"Critical"

**Pull request merged**
