### PR TITLE
Fixed protolathe not printing things that required reagents.

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/11823

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This doesn't actually change how many reagents are consumed in the process of making something; it only checks for if you have the required amount; it still actually uses/removes as much as is listed in the original design datum.

Ie: try upgrading the machine to make; the floral will require 7.5 radium. If you put 7.5 radium in it, it'll print and everything looks fine and dandy.

Now keep it upgraded and put in 25 units and print one off; check the chemical storage; it'll only have 5 units of radium left.

**Comment by xxalpha** [comment]
i fucking hate upgrades

**Comment by Dorsisdwarf** [comment]
Ready for merge?

**Comment by xxalpha** [comment]
Yes

**Pull request merged**
