### PR TITLE
Fixed storage not updating when joining cable coils.

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/10701
E: This bug happens with any stack object. Fixed for all stack objects.

### CODE REVIEW

**Comment by Aranclanos** [comment]
no, I'm not a fan of it. The problem is when they delete themselves, any object, not when stacks are merging eachother.

**Comment by xxalpha** [comment]
How do you suggest this be fixed then? It's the same thing as the unEquip proc, you have to call a proc that handles removing from storage wherever is needed.

**Comment by Aranclanos** [comment]
call the location of the object for some global proc, said proc under the storage path would handle the issue.
I think that's legit.

**Comment by xxalpha** [comment]
Ok it's a proc.

**Comment by Aranclanos** [comment]
doing this with both hands didn't break right?

**Comment by RemieRichards** [comment]
Please label the proc with something like
"this proc is called on the location of an atom when it is Destroy()'d"

**Comment by xxalpha** [comment]
No aran, it didn't. I am not sure what the unequip call was for, I tested without it and it still worked fine, no glitchy hands.

Added a comment.

**Pull request merged**
