### PR TITLE
Gave engineering cyborgs permanent magboots effect.

### PR DESCRIPTION
**Pull request by xxalpha**

### CODE REVIEW

**Comment by Jalleo** [comment]
Can this be a cyborg upgrade instead? That can be toggled.

**Comment by Dorsisdwarf** [comment]
hero

**Comment by xxalpha** [comment]
Nah, engineering needs it.

**Comment by Ergovisavi** [comment]
:+1:
No reason not to, I guess.

**Comment by GunHog** [comment]
Very useful! :+1:

**Comment by Cebasiz** [comment]
thank you god

**Comment by optimumtact** [comment]
Make it like the flashlight, an action button and a powerdraining item

**Comment by Supermichael777** [comment]
That flashlight drains way to much power. also they realy do need this because of how space wind and out lord and savior affect Borgs.  aoe emp resistance might be cool as a high tech Borg upgrade

**Comment by Razharas** [comment]
Well ok i guess

**Pull request merged**
