### PR TITLE
Changed protolathe code to use material container.

### PR DESCRIPTION
**Pull request by xxalpha**
For the sake of consistency, I also changed the destructive analyzer and experimentor salvaging all materials in the items they destroy, instead of just metal and glass.

### CODE REVIEW

**Comment by Razharas** [comment]
Wonderful

**Comment by Fox-McCloud** [comment]
I'd like to point out this:

Glass and Metal sheets are 2000 units per sheet, not 3750: https://github.com/tgstation/-tg-station/issues/11584

**Comment by xxalpha** [comment]
Items will have whatever materials they are pre-defined to have. It's really not my concern right now.

As for the 3750 in this code, I'll change the values to standard.

**Comment by Fox-McCloud** [comment]
I see. The reason I ask is because the autolathe doesn't work that way; it adjusts the materials in an item based on how expensive it was...thus why I was curious if the protolathe would set an item's materials manually when its created.

That said, that kinda opens a can of worms, too---because logically speaking, that would mean things lying around the station would have to have material amounts added to them--which would invariably lead to scientists wanting to loot telecomms storage every single shift.

**Comment by Razharas** [comment]
Is this ready?
@xxalpha

**Comment by xxalpha** [comment]
It is now.

**Pull request merged**
