### PR TITLE
Engineering Cyborgs can now change their cable coil color.

### PR DESCRIPTION
**Pull request by xxalpha**

### CODE REVIEW

**Comment by pudl** [comment]
please no
cyborgs who fix things will leave ugly random colors all over the place. red is the standard, usually used for repairs. other colors are for wire art

**Comment by Thunder12345** [comment]
Would it be too much work for too little gain to give borgs a coil that can change colour?

**Comment by GunHog** [comment]
I love the random colors! :+1:

**Comment by xxalpha** [comment]
Yes Thunder. At least I can't be bothered to do that, this satisfies me.

**Comment by SconesC** [comment]
Can we have it so using the cable in hand will change the color?

**Comment by Xhuis** [comment]
Scones has the right idea.

**Comment by xxalpha** [comment]
Ok.

**Comment by SconesC** [comment]
:+1:

**Comment by GunHog** [comment]
Perfect :+1:

**Pull request merged**
