### PR TITLE
Fannypacks and Dufflebags

### PR DESCRIPTION
**Pull request by dannno**
Adds Fannypacks:
- 3 slots, hold tiny items
- many colors, 3 currently available from clothing vendor

Adds Dufflebags:
- 9 slots at the cost of slowdown

### CODE REVIEW

**Comment by dannno** [comment]
I feel like 9 slots might not be enough, would like to hear opinions on that.

**Comment by Iamgoofball** [comment]
>slowdown

Make it 12 or 16 slots

**Comment by Steelpoint** [comment]
Is it possible to tie slowdown to the amount of items inside the dufflebag? So if you go over the normal item limit (Six items for example) you then suffer from slow down.

**Comment by tkdrg** [comment]
That would make them strictly better than backpacks, though, which defeats the point.

**Comment by Fox-McCloud** [comment]
Keep in mind the exponential nature of storage when you have just 1-2 extra slots, especially when you have things like boxes and other storage items, so 12 slots is a helluva lot of storage for only 1 slowdown.

**Comment by Jalleo** [comment]
We really need to rework storage on basically everything if people want to do powercreep like this.

**Comment by dannno** [comment]
I guess the max I can see working is like, 10 slots. so I'll just leave it at 9. this is good 2 go then.

**Comment by paprka** [comment]
slowdown is enough of a factor against having a lot of items. keep in mind slowdown stacks, so you'll walk incredibly slow with a duffle and a hardsuit/riot suit

**Comment by dannno** [comment]
can't really get around that without making them too OP.

**Comment by Jalleo** [comment]
a rework of slowdown and everything would be required to solve that issue @paprka

**Comment by tkdrg** [comment]
Adding all the duffel bag inhands would go over the inhand limit. Perhaps it would be wise to put this on hold until that problem is solved.

**Comment by dannno** [comment]
wait, really? shit. I didn't know we were THAT close.

**Comment by dannno** [comment]
when I tested it all of them worked though?

**Comment by tkdrg** [comment]
Yeah it works, but it means nobody can edit the inhands file anymore after this until we solve the problem. With the inhands that this PR adds, the file hits exactly the 512 limit.

**Comment by dannno** [comment]
eyyy perfect to merge then 8-DD

**Comment by paprka** [comment]
ill be refractoring inhands this week if i can get a .dmi freeze

**Comment by tkdrg** [comment]
@dannno Actually, looks like there's 8 bags and only 6 inhand slots, so 2 will be lost if this is merged right now. Your choice if you want to lose these or to wait for pap to fracture them.

**Comment by dannno** [comment]
I was kidding, it's obviously best to wait.

**Comment by dannno** [comment]
I guess this should be merged so that Paprika can begin.

**Comment by paprka** [comment]
well if the inhands don't work this shouldn't be merged, you can either remake it or whatever

**Comment by Nienhaus** [comment]
I made the fanny packs, and @MrSnapwalk made the base for the dufflebag which I made more of.

**Comment by dannno** [comment]
Thought it was yours, credit as in the commit, will correct in the new PR when it's time

**Comment by Nienhaus** [comment]
I was mostly meaning the dufflebags.

**Comment by dannno** [comment]
will make new when inhands shit is merged

**Pull request closed without merging**
