### PR TITLE
[WIP] completely removes virology

### PR DESCRIPTION
**Pull request by hornygranny**
consequentially, this also removes the monkey gamemode completely

problems: rev blight needs to be recreated as something else, slime disease too

### CODE REVIEW

**Comment by TheColdTurtle** [comment]
but viro is so fun

**Comment by Incoming5643** [comment]
www.niceme.me

**Comment by RemieRichards** [comment]
Absolute madman

**Comment by okaw** [comment]
Virology is so annoying though let's be real

**Comment by KazeEspada** [comment]
Viro is bad, but really? During a code freeze?

**Comment by RemieRichards** [comment]
@KazeEspada Feature Freeze*

**Comment by Incoming5643** [comment]
To be clear here I disagree utterly with this pull. 

Even if virology had absolutely no merit as a job virology still provides a much needed hiding place for all sorts of things.

So I really hope you're just memeing on us

**Comment by Anonus** [comment]
That, and it was useful as a system for doing things like revenant blight(though reagents would work for it I guess)

**Comment by Incoming5643** [comment]
Also the loss of monkey mode is indefensible

**Comment by RemieRichards** [comment]
@Incoming5643 monkey mode needs to be made into Ape Escape anyways, we already have the hats...

**Comment by Ausops** [comment]
what necessitated this change

**Comment by MrPerson** [comment]
>caring about monkey mode

**Comment by Bawhoppen** [comment]
I will blindly support HG :+1:

**Comment by Zilenan91** [comment]
I can't agree with this unless we replace viro with something, diseases are a lot of fun.

**Comment by RemieRichards** [comment]
disease are alright, but their core code is... it's kinda trash.
it's due for a rip-out+redo

**Comment by Zilenan91** [comment]
Doesn't this also break xenos and those new Op nades?

**Comment by Bawhoppen** [comment]
@zilenan91 check the WIP tag

**Comment by hornygranny** [comment]
@Zilenan91 xenos no, op nades yes

**Comment by AlexanderUlanH** [comment]
The job sucks but the code behind diseases is fine, as is the design of advance diseases.
:-1:

**Comment by Supermichael777** [comment]
improve don't remove. also remove game modes entirly while your at it

**Comment by Fox-McCloud** [comment]
:-1: 

The disease backend is wonky, but a good system--it's just horrendous underutilized. It's certainly better than Bay's shitty Virus2 system.

**Comment by Cheridan** [comment]
>removing monkey mode

unforgivable

**Comment by swankcookie** [comment]
Is it NOT possible to just remove the job and work space without removing the supporting disease code?

**Comment by Bawhoppen** [comment]
isn't the whole point that its bad code

**Comment by swankcookie** [comment]
Is it? It seems like a lot of support for this comes from the unused  job. Is deleting it all reallythe best choice?

**Comment by Aranclanos** [comment]
lol freeze eat shit hg

**Comment by LanCartwright** [comment]
I'll make virology fun again, starting off we buff viruses.

**Comment by PKPenguin321** [comment]
How could this even be considered a good idea
I don't understand you people
:-1:

**Comment by PKPenguin321** [comment]
codecuck no codecucking! codecuck no codecucking! codecuck noooo codecucking!

**Comment by KazeEspada** [comment]
Hornygranny is just a big baby and thinks everything should go his way.

**Comment by phil235** [comment]
:-1: Improve, not remove.

**Comment by GunHog** [comment]
This does not need to exist, and is not even properly implemented. :-1:

**Comment by duncathan** [comment]
As much as I believe in remove don't improve this is dumb :-1:

**Comment by duncathan** [comment]
Also freeze you cuck

**Comment by Iamgoofball** [comment]
@hornygranny fix your shit

**Comment by PKPenguin321** [comment]
g r a n
g r a n
c o d e
c u c k

**Comment by Zilenan91** [comment]
quick nobody comment so he forgets this exists

**Comment by GunHog** [comment]
Why is this open again? :-1: It is a terrible decision which has no place in this codebase.

**Comment by feemjmeem** [comment]
:-1: Personally I don't approve of removing a job and everything it touches because there is some bad code associated with it.

**Comment by Incoming5643** [comment]
Still not a good idea :-1:

**Comment by Anonmare** [comment]
Improve don't remove :^)))

**Comment by drynwyn** [comment]
massive code cuck

**Comment by Aranclanos** [comment]
rejected so everyone can love me

Also usually for stuff like this, you should kinda have an explanation instead of just being a blank description. Dunno your motives besides you being a gigantic cuck.

**Comment by duncathan** [comment]
absolutely dominated

**Comment by swankcookie** [comment]
This can't really be taken as anything but meming. The blank description... 
I mean come on.

**Comment by PKPenguin321** [comment]
>aran does something right for once

all hail the new god

**Pull request closed without merging**
