### PR TITLE
"The Net" barsign

### PR DESCRIPTION
**Pull request by xxalpha**
Since I can't sprite for shit I'll leave the judgement of the quality of this barsign to other people. If I see a few rejections I'll close this myself. Also head of sprites @WJohn.

barsign

last feature pr WINTER IS COMING

edit: less shitty now

edit2: now standard size (it's actually one pixel wider but you wouldn't notice if i didn't tell you)

### CODE REVIEW

**Comment by Xhuis** [comment]
Not bad.

**Comment by xxalpha** [comment]
fuck i had a better idea

**Comment by optimumtact** [comment]
I like it

**Comment by Nienhaus** [comment]
It is pretty cool.

**Comment by xxalpha** [comment]
nienhaus approves :speedboat:

**Comment by GunHog** [comment]
:+1: Add pl0x. I will totally set this one all the time!

**Comment by Niknakflak** [comment]
It's too big for the wall.  The barsigns sit on walls, this one looks like it is the wall.

**Comment by xxalpha** [comment]
I didn't notice that somehow. Thanks @Niknakflak

**Comment by Nienhaus** [comment]
Also only pinging WJohn in the first post. wowe
:p

**Comment by xxalpha** [comment]
I heard you say you didn't sprite no more, so I figured you quit as the head of sprites.

**Pull request merged**
