### PR TITLE
Adds an empty hugbox.

### PR DESCRIPTION
**Pull request by xxalpha**
As requested by @palpatine213

### CODE REVIEW

**Comment by bustygoku** [comment]
Isn't there one of these on the map already? You might need to change its path to be the medical one.

**Comment by WJohn** [comment]
I thought we had a variable called "empty" specifically to make medkits start empty, like those found in robotics.

**Comment by xxalpha** [comment]
I didn't see one so I didn't change anything.

**Comment by xxalpha** [comment]
This isn't a medikit WJ, it's a box.

**Comment by MrStonedOne** [comment]
xxalpha, you can test by commenting out the hugbox, and compiling all the maps to see if runtimes happen.

**Comment by xxalpha** [comment]
It's not in any of the dmms, it seems.

**Comment by JJRcop** [comment]
hug/medical doesn't exist!!!!!

**Comment by RemieRichards** [comment]
@JJRcop defining that New() statement actually creates the type.

**Comment by Ikarrus** [comment]
@xxalpha I put one in perma

**Comment by JJRcop** [comment]
@RemieRichards Oh, I see, hah.

**Comment by xxalpha** [comment]
@Ikarrus where exactly? We had a few map merges, it probably got removed.

**Comment by Ikarrus** [comment]
@xxalpha It looks like it was removed by @Steelpoint without notice

**Comment by xxalpha** [comment]
Added hugbox to box perma.

**Pull request merged**
