### PR TITLE
Adds Plasteel module for Engineering cyborgs.

### PR DESCRIPTION
**Pull request by xxalpha**
Plasteel module for engineering cyborgs specs:
 - 10 plasteel sheets maximum
 - Long ass recharge time

### CODE REVIEW

**Comment by GunHog** [comment]
I myself like this :+1: , but you probably are going to get a LOT of pushback on this. Be warned.

**Comment by AndroidSFV** [comment]
I can see it now:

Roboticist: "Engineering borg, build my mechs for me with your plasteel."

**Comment by WJohn** [comment]
They already produce lots of metal by deconstructing computer/machine frames.

**Comment by SconesC** [comment]
A bit of balance concern comes to mind

Engiborg core fortifications are going to get NEXT LEVEL meaning its going to become meta to bring a chemist in your siege crew. Going through rwalls is a pain in the ass.

**Comment by WJohn** [comment]
Chemists are already brought into the AI fight a lot of the time.

**Comment by Anonus** [comment]
I, uh, don't think this is a good idea, if mostly for the malf and traitor AI implications.
Those AIs are going to be basically unkillable without absurd amounts of thermite(it's like 20 per rwall) or bombs. Not one bomb, multiple bombs, because one borg can easily have enough time to cover the entire sat with rwalls.

**Comment by AlexCrimson** [comment]
Yeah this fucks with the balance. Engiborg will be able to wall in aliens completely. No doubt there are plenty of other things they could abuse.

By all means add it, but i suspect it will either require reverting(lol) or you all will nerf rwalls because of it.

**Comment by SconesC** [comment]
"wall-fortress 9000 on the horizon, captain"
"whats the plan of attack"
"well the engiborg has 5 solid layers of rwalls there"
"bring out the multiple maxcaps and thermite, i guess, isnt this fun and interesting?"

**Comment by xxalpha** [comment]
Are you saving up that thermite and max cap bombs for something else? Is it mining? Are you mining with bombs? Is that what the bombs are for and can't be spared for anything else?

**Comment by SconesC** [comment]
@xxalpha the joke is that this is not balanced because the crew does not often have those things because malf play = agressive early play

**Comment by xxalpha** [comment]
I reduced the uses amount to 10 and reduced recharge rate so it takes about 4 minutes to recharge from zero to full.

This should make a reinforced wall fortification a much less viable strategy as it takes too much time without an army of engineering cyborgs.

**Comment by SconesC** [comment]
i think it's just that they can make rwalls at all that's an issue

**Comment by optimumtact** [comment]
From what I can recall Rwalls were left to humans so that the borg wouldn't be a completely superior replacement for engineers and atmospheric techs.

They're already pretty much a superior choice for most building and repair tasks since they do not need to breathe and work in any temperatures.

**Comment by xxalpha** [comment]
A human engineer can carry a big stack of plasteel, though.

**Comment by Cheridan** [comment]
What do they need plasteel for building in the first place? Nothing besides rwalls really, which they don't need because as was said, it would really ruin the balance of a lot of things.

**Comment by xxalpha** [comment]
Repair rwalls.

**Comment by PKPenguin321** [comment]
>potentially making a game-changing balance issue that could completely ruin malf

>so engieborgs can repair r-walls

**Comment by Kelenius** [comment]
>Because malf is overpowered and doesn't need any buffs

**Comment by xxalpha** [comment]
I think you people are overestimating this plasteel module. You can only build 5 rwalls per 5 minutes you can't do huge core fortifications at such a slow build rate in a time useful for Malf, since you have hacked APCs that can't be seen all over the station, not to mention security could look at your core at any moment. If the Malf AI gets a bunch of engineering cyborgs and gets them all with plasteel modules, why shouldn't it rip the benefits?

Also Aliens were pointed out, there's no way an alien is going to let you wall it at one rwall per minute.

**Comment by Dorsisdwarf** [comment]
handy trick: 
Just rwall the lobby door, the core door, and the 3 windows out back that people use to break in.

bam, 5 rwalls (2 of which can be hidden under the doors) and it's triple hard to get into the core.

**Comment by Razharas** [comment]
Haedcoder said bad balance, closed

**Pull request closed without merging**
