### PR TITLE
Nuke deconstruction rework 

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/11570
Fixes https://github.com/tgstation/-tg-station/issues/10876

 - More standardized deconstruction steps
 - Can partially repair the nuke to stop radiation leak
 - Rebalanced plutonium core radiation
 - Portable nuke, self-destruct terminal, syndicate screwdriver, nuke core container and nuke core have new sprites
 - Vault circuit floors are blue to match new sprite

All sexy new sprites done by @Wjohn, scroll down for screenshots.

nuke1
nuke2
nuke3
nuke4
nuke5
nuke6
nukegif

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Can you add climbing on the nuke?

**Comment by xxalpha** [comment]
Good idea, but I'll leave that to another PR.

**Comment by Dorsisdwarf** [comment]
I don't like the new station self-destruct nuke. It just looks so... tiny.

**Comment by xxalpha** [comment]
No need to overcompensate, @Dorsisdwarf.

**Comment by Iamgoofball** [comment]
@WJohn can you redo the station self-destruct to have the nuke coming out of the top like the last one, but with the new nuke sprite?

**Comment by xxalpha** [comment]
No that was ugly af

**Comment by Anonus** [comment]
Aw, my core container sprite. ;_;
I mean, the new sprite has more depth but it doesn't have the cool scrolling S and that makes me Sad.

**Comment by Dorsisdwarf** [comment]
Can you post a gif of what the room looks like when the nuke is activated?

**Comment by xxalpha** [comment]
Updated OP with gif.

**Comment by Dorsisdwarf** [comment]
For reference: Current Sprite:

**Comment by PKPenguin321** [comment]
to be honest i'm not a fan of the new portable nuke sprite
round the end instead of having a cartoony orange cone

**Comment by xxalpha** [comment]
How is that cartoony? That's what missiles/warheads look like.

**Comment by Core0verload** [comment]
New portable nuke sucks. Everything else is :+1:

**Comment by Shadowlight213** [comment]
Yeah. Have to agree, portable nuke is a bomb. New sprite doesn't look like one.

**Comment by xxalpha** [comment]
Portable nuke is a makeshift bomb, it's a nuclear missile warhead with a keyboard.

What do you think bombs look like?

**Comment by Tophwells** [comment]
>What do you think bombs look like?

I think the inspiration is this:
https://en.wikipedia.org/wiki/File:Little_boy.jpg

**Comment by Core0verload** [comment]
I think the inspiration is this:
kawue
Awww!

**Comment by Anonus** [comment]
Those look a lot like the current nuke sprite, though...

**Comment by Anonus** [comment]
The screenshots in the OP are OUTDATED and it is currently surrounded by blue tiles and not green tiles.
And that looks really odd.

**Comment by xxalpha** [comment]
It's matching the new sprite.

**Comment by Shadowlight213** [comment]
@xxxalpha matching the sprite is not a good thing when it causes the nuke terminal to blend into the floor around it.

**Comment by Core0verload** [comment]
How about changing the bomb sprtie to be more bomb-like?

**Comment by xxalpha** [comment]
No.

**Comment by Core0verload** [comment]
Then it still sucks.

**Pull request merged**
