### PR TITLE
Adds surgery table and tools to the Nuke Ops ship.

### PR DESCRIPTION
**Pull request by xxalpha**
Requested by scones.

scrnshot1

-------------
Update: This also fixes the stair tiles being honk tiles.
scrnshot1

### CODE REVIEW

**Comment by TheVekter** [comment]
Before anyone else asks like I did: Plastic Surgery and Augmentations.

**Comment by Xhuis** [comment]
1. Augs can't be acquired afaik without buying a borg and disassembling it (which is fucking stupid)
2. If you actually do stealth ops, plastic surgery seems fine to me and also helps prevent meta

**Comment by xxalpha** [comment]
There are two robot arms on the left table.

**Comment by Xhuis** [comment]
Augmenting a single or both of your arms seems kinda worthless when 99% of the time people are aiming for your head or chest.

**Comment by xxalpha** [comment]
I don't know if it was fixed, but you can augment whatever part of your body you wish with any of the robot parts.

**Comment by Fox-McCloud** [comment]
:+1:

Plus, if the idea to have a "mercenary" game mode (kill so many people, steal items, capture someone, and retrieve an item implanted into someone) as was proposed a while ago, this will help them yank said item out of the person.

**Comment by dannno** [comment]
@xhuis stop being a shit in the mud

**Comment by AndroidSFV** [comment]
In before suicide bomber ops

**Comment by paprka** [comment]
The robot arms were for making medibots originally, you nuke ops are damn creative

**Comment by babinsquared** [comment]
drag the captain kicking and screaming from the station to remove the disk he has implanted in his body
:+1:

**Comment by SconesC** [comment]
I suggested this primarily for plastic surgery, by the way

Stealth ops are waaaay stronger when they don't have to voicechanger

**Pull request merged**
