### PR TITLE
Fixes the straightjacket

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/5819 : 
 - Now it's possible to resist out of a straight jacket (takes roughly 5 minutes)
 - Straightjacketing someone who is handcuffed will not remove the handcuffs

### CODE REVIEW

**Comment by Bawhoppen** [comment]
:-1: 
0/10 don't fucking remove fun

**Comment by TheWiznard** [comment]
@Bawhoppen how is being permanently out of the round fun? and don't say "just get someone to un-straightjacket you" because it never happens

**Comment by Bawhoppen** [comment]
not everything has to be fun for the user
don't get yourself straight jacketed like a retard

**Comment by Iamgoofball** [comment]
@Bawhoppen if you have access to a straightjacket, in the same room and general area you can find:
knockout chems
cuffs
beds to cuff to

you can use all 4 of these in combination to ensure someone is stuck in place for maybe 20-30 minutes

think about that before you bitch

**Comment by Bawhoppen** [comment]
we have had countless other discussions about straight jackets and they always end with the pro-straight jacket side winning

save it for another PR is what I'm saying, don't try and bundle it and call it a fix

**Comment by Iamgoofball** [comment]
the issue report literally says "You cannot resist out of them"

**Comment by Bawhoppen** [comment]
just because someone made a shitty feature request issue means that it needs to be fixed?

**Comment by duncathan** [comment]
More like because someone made a shitty feature tbh
I'm undecided whether to call this PR a feature or not so I'll use the time tested maintainer technique of just waiting for someone else to decide

**Comment by PKPenguin321** [comment]
i will decide for you fam
its not a feature and its 100% freeze friendly, trust me

**Comment by hornygranny** [comment]
correct solution here :+1: https://github.com/tgstation/-tg-station/pull/3753

**Comment by Steelpoint** [comment]
Straightjackets do have some strategic uses, mainly for Cult rounds but also in some edge Wizard rounds.

They are very useful in conjunction with other containment methods to keep someone locked down hard, though its rare to see this happen and is oft reserved for either high level antags (like listed above) or top tier shitters that are, instead of executed, given this as a punishment.

**Comment by PKPenguin321** [comment]
I thought we used muzzles on wizards, not straitjackets. Why would we even need to straitjacket a wizard?

**Comment by PKPenguin321** [comment]
Ayy

**Pull request merged**
