### PR TITLE
Replaced Disabler module with Advanced Taser module for Secborgs.

### PR DESCRIPTION
**Pull request by xxalpha**
Cyborgs are supposed to be the best at their assigned functions, a peace keeping borg needs a robust non lethal ranged weapon.

### CODE REVIEW

**Comment by MMMiracles** [comment]
I thought the whole purpose of them loosing the taser in the first place was to stop them from shitting on antags so much? Unless you manage to flash it or are packing EMPs, one security borg can easily fuck your day up already, even more-so with a VTEC and the cooldown module.

**Comment by xxalpha** [comment]
Antags are equipped enough to deal with cyborgs.

**Comment by Jalleo** [comment]
I got to agree with @MMMiracles the borg is still able to take people down its better this way. If they get adv taser it will become more powerful than a standard officer in moet circumstances

**Comment by xxalpha** [comment]
Nah man. Cyborg stuns = paralysis, muteness and deafness. Stun a cyborg and you win and antags have ways to stun borgs.

**Comment by Cheridan** [comment]
>one of the top two cyborg modules needs a buff so it can stomp out fun betterer

yeah no

@xxalpha try not getting stunned then. you can't really play a job with only two counters and then complain that you got countered

**Comment by Anonus** [comment]
>buffing secborg, the most antag-shitting borg
yeah no

**Comment by xxalpha** [comment]
Traitors can buy an emp kit for cheap that comes with a multi use EMP implant. This is enough to kill or subvert any cyborg that comes after you.
Changelings have their emp screech.
Cultists have their EMP papers.
Nuke Ops have ion rifle and can also buy EMP kits.

Every antag has an AOE stun. Why are you defending the antags?

**Comment by Iamgoofball** [comment]
Don't forget the EMP flashlight.

**Comment by xxalpha** [comment]
Well yeah, the EMP kit has an EMP implant, a couple of EMP grenades and the EMP flashlight. It costs 5TC. No excuse.

**Comment by Iamgoofball** [comment]
That's a lot of TCs for a "just in case" weapon that can shock all the doors in the area and get me killed, along with alerting the AI immediately.

**Comment by GunHog** [comment]
Flash. Any human antag can acquire one by breaking into tech storage or robotics. Melee range is suicide for borgs because of this.

**Comment by xxalpha** [comment]
@iamgoofball If you're so afraid of a cyborg haunting you, it's not a just in case option. On the other hand, how many cyborgs do you see compared to humans?

**Comment by GunHog** [comment]
Thank you, xxalpha, for having the bravery to do what even I have not the courage to try.

**Comment by MMMiracles** [comment]
This may of not been as such as a huge issue before posibrains and what-not, but cyborgs are too easy to build right now for there to be a module solely dedicated to shitting on antags.

Even if you don't get that many people for borging, theres always the roundstart borg and the 3-4 observers/deadchat wanting to get in on it with posibrains.

**Comment by Anonus** [comment]
If robotics isn't full of idiots there are regularly 3-5 borgs, which can potentially all be secborgs.

**Comment by xxalpha** [comment]
>a module solely dedicated to shitting on antags.

A racist mind is a racist kind. In this case, replace racist with validhunting.

I play cyborg to follow laws, not to hunt antags. Part of the appeal of cyborgs is their efficiency. Disablers are intentionally inefficient.

**Comment by GunHog** [comment]
Is it so awful that antags have more than one type of enemy to fight? Must they have a one-size-fits-all method of neutralizing threats?

**Comment by Cheridan** [comment]
>Flash. Any human antag can acquire one by breaking into tech storage or robotics. Melee range is suicide for borgs because of this. 

Then don't get into melee range, holy shit. Again, you can't complain that an antag took steps to prepare for your job by getting your hard counter and wrecking you with it.

**Comment by GunHog** [comment]
That was in reply to Goofball stating that traitors need to invest TC to handle silicons. If I was against the counter, I would say so.

**Comment by MMMiracles** [comment]
@xxalpha 
Yeah well it doesn't help when the stereotype of the valid-hunting security borg is so common its more or less become the standard. I can name maybe, 1-2 borgs, that I've seen use their place to actually uphold their laws instead of being ROBOCOP.

**Comment by xxalpha** [comment]
That sounds like an administrative problem and has nothing to do with tasers.

**Comment by Anonus** [comment]
Explain why giving secborgs a one-hit ranged stun is good, exactly?

**Comment by Ergovisavi** [comment]
Absolutely not. Secborg is PLENTY powerful with a disabler. Also, tasers are shit gameplay.

:-1:

**Comment by xxalpha** [comment]
Why the bias against cyborgs, though? Security and antags both have ranged one hit stuns.

**Comment by Ergovisavi** [comment]
* Secborgs are almost entirely played by validhunting shitters
* Incentivizes players to play human security instead of validhunting as a stuntank 9000, more human security players is a good thing
* Flashes, while easily obtained, are not a viable counter in most use cases against a security cyborg that is actively going for you, unless that cyborg is fucking terrible

In all honesty secborg should just be outright removed, but where we're at with a disabler isn't terrible either.

**Comment by bgobandit** [comment]
pretty sure most secborgs play secborg because the AI orders them to

**Comment by xxalpha** [comment]
>In all honesty secborg should just be outright removed,

Well then.

**Comment by daman997** [comment]
sec borgs are cancer already
no :-1:

**Comment by M3hillus** [comment]
:-1:

**Comment by Jalleo** [comment]
If you want you could make it a upgrade module that requires a actual adv taser for the sec borg to get it. This would probably balance it out.

**Comment by SconesC** [comment]
:-1: Instant borg tase was removed, as-is you can actually win against a secborg ambush sometimes

**Comment by Iamgoofball** [comment]
:-1:

**Comment by Kromgar** [comment]
:-1: 

Silicons should never be as good as humans or better than them

**Comment by Aloraydrel** [comment]
Please no

**Comment by xxalpha** [comment]
>Silicons should never be as good as humans or better than them

Top. Kek.

**Comment by Miauw62** [comment]
Secborgs can already down you in two (iirc) hits with the disabler, and the
only "free" counter (gl getting flashes when robotics uses all the
roundstart ones on borgs) is melee range.

It's nice to handwave it as an "administrative issue", but we code mainly
for tgstation and most of our downstreams are similar anyway. What we see
is secborgs relentlessly validhunting, with few exceptions. I very much
support an improved silicon policy to reduce this, but code changes can
mean a lot too. In both directions.
Op 27-aug.-2015 22:23 schreef "xxalpha" <notifications@github.com>:

**Comment by xxalpha** [comment]
Considering cyborgs have no way to stop humans non harmfully, since flashes don't knock you down anymore, you'd think at least one cyborg would be extremely well equipped to CC humans.

Good luck trying to stop more than one person with disabler if you want to break up a fight.

**Comment by Supermichael777** [comment]
I have to agree Secborgs do attract the same valid-hunting shits that go prowling mant with lit stun-prods in their packs, but putting a ridiculous burden on all Secborg players because of a few shitlers who realy should be told off or job banned for policy violations is harmful to the experience of people who actually follow the rules. The argument could be made that Secborgs need to be cut to help move away from stun combat. Such a big decision should get input from the staff, forums, and in game poling; however until then it should be restored to its full potential as the AI's non-leathal weapon. I believe that telling the AI in a message to ensure its Borg follows its laws and to lock it down if it disobeys laws or instructions would be helpful in correcting some of the oversight issues.
Additionally Secborgs should be retooled into a less overtly valid-hunting duty. Changing its name and color scheme might help, as well as modules that let it do things other then straight combat. perhaps more investigative tools such as the forensic and chemical scanner. For the name I suggest Safety Borg to help emphasize that its role should be protecting people instead of hunting people down and a light blue color scheme. Its current shape and color-scheme is too military for my taste.

**Comment by Lumipharon** [comment]
Well considering you can keep multiple people stunned with a disabler far more efficiently then with a taser, yeah.

Sec borgs lost tasers for a fucking reason.
Spending a quarter of you TC's in case you get UTTERLY HARD COUNTERED by a borg, or having a flash an hoping the borg comes within melee range before tasing you, is retarded.

Just because something has a counter, doesn't mean it's healthy for gameplay.
You might as well say every crew should have tasers, because antags can just emp them :^)

**Comment by Durkel** [comment]
Security borgs have been and will always be a form of malignant cancer, and giving them better tools to shit on people isn't going to help that problem at all.

You have a stun baton , the ultimate close range weapon, and a disabler that can shit 15 or more shots down a hallway to stop someone. You already have all the tools you need.

**Comment by Supermichael777** [comment]
Once again i think the primary problem with Secborgs is they don't have enough non weapon tools to do their job so their stuck as the wet blanket valid machine. I feel reagent and forensic scanners could help this, as could additional duties and tools

**Comment by Fox-McCloud** [comment]
:-1: 

Yeah, no. Secborgs are still ultra-robust stun-tank 5000's, even with disablers; they don't need a buff to make them a nigh uncounterable antag-hunter 6000.

**Comment by PKPenguin321** [comment]
secborgs are already awful fun-stomper 9000s that should just be removed
why the fuck are you buffing them this is stupid :-1:

**Comment by MrPerson** [comment]
Giving secborgs a buff is a very strange way of removing them

**Comment by optimumtact** [comment]
:-1: what were you thinking?

**Comment by Dawgas** [comment]
I don't care what the fuck's happened over the past few years to make the playerbase entirely unrobust

if you can't fucking evade detection then you shouldn't bitch if you get your shit kicked in, although yes, borgs are still strong, even after all the nerfs they've gotten over the years, but that's what actually getting good at the game is for. This pull request seems to adequately allow the security borg to do what its supposed to be capable of doing - I would recommend other changes instead of stopping this pull, but increasing movement speed is a discussion best done elsewhere, isn't it?

**Comment by ExcessiveUseOfCobblestone** [comment]
Fuck RedBots :-1: 

I wouldn't be opposed to this if Taserbeams McValidzzz didn't treat Asimov as Robocop Jr.

Yes, this is a player problem, so until THAT problem gets fixed, I don't think it makes sense to give them things like tasers that promote said behavior.

Maybe we should do to borgs what we do to sec and bwoink per each crime :^)

**Comment by xxalpha** [comment]
I don't understand, there's a whole department with the purpose of validhunting with all the tools of the trade, but cyborgs having a taser is bad even though they are restricted by silicon laws and can't validhunt.

Yet you keep saying the secborgs are the validhunters.

**Comment by GunHog** [comment]
Because they only accept that Security players are valid hunters. Players do not seem to want the silicons valid-hunting, and Secborgs are considered among silicon players, not Security players. Therefore, the thought of a borg version of a Sec officer is hard for them to swallow.

**Comment by Lo6a4evskiy** [comment]
Humans have a shitload of counters, cyborgs have only two, one of which is extremely hard to use due to being melee range and another costs a lot of precious TC. Having uplink items that are basically necessary to buy in order not to get dunked is shitty.

I don't understand, why do you think that security cyborgs are lacking in power?

**Comment by Steelpoint** [comment]
I was the person to replace secborgs taser with a disabler. I still support my at change.

The main reason I proposed that change was both to make the secborg less powerful against antagonists, but also against regular crewmembers.

In 1v1 situations the Borg will usually win since it has the support of the AI and it can get the drop.

What the disabler change did was make the Borg less effective against groups of people.

**Comment by Actionb** [comment]
Voicing my opinion just in case someone still thinks this PR should go through:
Secborgs don't need tasers. Don't do it. If they are too unrobust to hit a target three times they always have the option of going in with a baton, being immune to almost everything 'n all...

**Comment by xxalpha** [comment]
>What the disabler change did was make the Borg less effective against groups of people.

Yes and this is a bad thing, Steelpoint. Sec officers have, in addition to their tasers, flashbangs, purely for crowd controlling. Have you tried stopping more than two people with a disabler? You'll just look like an asshole pew pewing everywhere and accomplishing only a few short naps.

**Comment by Miauw62** [comment]
"gee security has an overpowered and shitty thing they can use to fuck over people"
"I BETTER BUFF SECBORGS SO THEY CAN BE EQUALLY SHITTY"

**Comment by xxalpha** [comment]
Secborgs had their taser removed and everything else stayed the same, Miauw. If there were any legitimate problems, it wouldn't be just the secborgs losing their tasers. The nerf was a case of i ded pls nerf.

**Comment by ExcessiveUseOfCobblestone** [comment]
>cyborgs having a taser is bad even though they are restricted by silicon laws and can't validhunt ... Yet you keep saying the secborgs are the validhunters.

Yes because most people use Secborg, despite their asimov lawset, to uphold Space Law [AKA Validhunt].

There are reasons why some sec officers asked to get borged so they can go into Secmodules, and I don't think it's because they want to be constrainted to asimov law. Secborg is still an upgrade from the normal human bean, even with the disabler nerf.

If the problem is CCing, use your baton. One hit Stuns BUT you have to get in close enough for the individual to be able to counter you. That's more than fair balancing given the power of secborgs.

**Comment by xxalpha** [comment]
>Yes because most people use Secborg, despite their asimov lawset, to uphold Space Law [AKA Validhunt].

Administrative problem. But I am sure admins will react if you ahelp.

Besides, not having a taser is not going to stop those people from being bad.

**Comment by MMMiracles** [comment]
Well, theres 5 roundstart slots for an officer + whatever the hop decides to open, vompared to the 1 max roundstart borg and the few extra borged crew, so odds are you're more likely to see shitty officers.

I still cant recall more than 2 sec borgs max who didnt treat a sec module as non-lethal robocop. Its an issue with this playerbase having some shit player who play solely for valids, and buffs like this only encourages them to be even more shitty. 

Its apparently more than an adminstrative issue considering some codebases like goon have even outright removed the security module for being shit. It literally serves no purpose but to stop and detain, which kinda makes it automatically lean towards following space law and coming up with shit law 1 excuses for non-harmful acts because "breaking DA RAW is harmful"

AKA remove sec borg you are worst borg

**Comment by xxalpha** [comment]
A cyborg with weapons is necessary for traitors who subvert and traitor/malf AIs.

I read "remove secborgs" as "stop playing in ways I don't like".

**Comment by ExcessiveUseOfCobblestone** [comment]
TBH the fact it's called SECborg, it's red, and anything else that relates it to the Security department [and by extension saying it's okay to be a space-law hunting sillycon] gets on my nerves. It should NOT be security, it should be upholding its laws.

> I read "remove secborgs" as "stop playing in ways I don't like".

Isn't that the point of why we don't want them to have tasers? We DON'T like the way they're played currently so we don't want them getting buffed.

**Comment by MMMiracles** [comment]
Traitor AIs/malf/emag can give borg modules already unique shit. All get stunarms. Sec gets lasers (add an upgraded cell with this and holy fuck death incarnate), janitor gets refillable lube, med gets refillable acid, and standard gets a fucking esword+baton. Just about every borg when hacked is capable of killing, and the sec borg is already extremely good at that. The taser only makes the sec module even more appealing for mass-murder.

**Comment by SconesC** [comment]
They're fine right now, if you need to control groups of people it's not hard to aoe flash and disable/baton

**Comment by xxalpha** [comment]
Should I give them flashbang launchers?

**Comment by xxalpha** [comment]
>Isn't that the point of why we don't want them to have tasers? We DON'T like the way they're played currently so we don't want them getting buffed.

That doesn't stop shitters. I just played a round where a secborg was allowing security to forceborg, with Asimov lawset. It not having taser did not prevent it from validhunting. Why can't it have a taser? It' useful for Law 1 reasons, for people who subvert silicons and for antag AIs who just need muscle. They are NOT fine.

**Comment by GunHog** [comment]
The module does not matter in regards to a borg allowing Sec to brain people by force. It is a violation of Law 1 if the prisoner is alive, yet does not consent. Now, actually trying to stop Sec harming people is near impossible, and you will be locked/blown for trying, but at the very least you are not allowed to assist them.

**Comment by Robustin** [comment]
Thumbs down, I haven't anything to add that hasn't been said already... AI and its borgs don't need any more buffs to their Harmyeller McValidHunt 9000 toolkit.

**Comment by RemieRichards** [comment]
@Robustin ```:-1:``` is thumbs down, ```:+1:``` is thumbs up

**Comment by xxalpha** [comment]
Oldman not so robustin.

**Comment by Razharas** [comment]
Secborgs are fine

**Pull request closed without merging**
