### PR TITLE
oranges is masterrace

### PR DESCRIPTION
**Pull request by doubledankmemes**
oranges is masterrace

### CODE REVIEW

**Comment by TheColdTurtle** [comment]
oh thank goodness for the checks

**Comment by optimumtact** [comment]
stop

**Comment by optimumtact** [comment]
stop

**Comment by tedward1337** [comment]
the bot was kicked from coderbus
this is useless now

**Comment by optimumtact** [comment]
there's a joke and then there's taking it too far you autist fuck

**Comment by doubledankmemes** [comment]
there's a joke and then there's taking it too far you autist fuck

**Pull request closed without merging**
