### PR TITLE
Fixed T-Scanners runtime error

### PR DESCRIPTION
**Pull request by xxalpha**

### CODE REVIEW

**Comment by phil235** [comment]
what was the runtime?

**Comment by xxalpha** [comment]
null T a bunch of times

**Comment by xxalpha** [comment]
The following runtime has occured 37 time(s).
runtime error: Cannot read null.intact
proc name: scan (/obj/item/device/t_scanner/proc/scan)

**Comment by xxalpha** [comment]
WAIT A MINUTE

**Comment by xxalpha** [comment]
Ok now it should be fixed, I was looking at the wrong check. I am sure this is the one causing the runtimes because the engine goggles aren't runtiming and they have the null check.

**Pull request merged**
