### PR TITLE
A handful of fixes.

### PR DESCRIPTION
**Pull request by xxalpha**
~~Unreported.~~

edit: Also Fixes https://github.com/tgstation/-tg-station/issues/5782
Weird ass runtime, but it happened at least once somehow. Miauw forgot to fix it so here it is.

edit: Also Fixes https://github.com/tgstation/-tg-station/issues/6748

edit: Also Fixes https://github.com/tgstation/-tg-station/issues/6283
edit: Also Fixes (unreported?) emitters not being reflectable.

### CODE REVIEW

**Comment by Incoming5643** [comment]
When you consider how many important systems use shuffle and how poorly byond handles runtime errors this is kind of a comically huge bugfix. I wonder what kinds of problems this caused

**Comment by xxalpha** [comment]
I saw it happen when I was trying to reproduce another bug, completely unrelated. It was Pete that was trying to attack something, I think, and it runtimed.

**Comment by optimumtact** [comment]
This doesn't seem right to me, either byond has 0 based arrays, in which case you need to go from 0 : len-1

or it has 1 based arrays in which case 1:len should be the correct usage.

**Comment by MrPerson** [comment]
BYOND's lists are 1-indexed. I usually do for(var/i = 1; i <= list.len; i++) and that works just fine.

**Comment by optimumtact** [comment]
Yeah sorry, that ++i threw me, good catch @xxalpha although I agree that i++ seems more sensible to me.

**Comment by xxalpha** [comment]
It was actually rand() that runtimed.

**Pull request merged**
