### PR TITLE
Make foam transparent and cover everything including mobs.

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/5965
Fixes https://github.com/tgstation/-tg-station/issues/12275
Closes https://github.com/tgstation/-tg-station/pull/14201

 - Foam layer is now higher than MOB_LAYER
 - Foam sprite is transparent (yes you can click on objects under the foam)
 - Changed all bots layer to be MOB_LAYER

scrnshot2
scrnshot3

### CODE REVIEW

**Comment by ChangelingRain** [comment]
>above mobs
>not above cleanbot

what LAYER are bots, anyway

**Comment by xxalpha** [comment]
FLY_LAYER for whatever fucking reason. All bots are, with the exception of mulebot.

I considered changing it but I can't be sure if people will get mad at bots being on mob layer.

**Comment by RemieRichards** [comment]
bots are mobs now, and should just go on the mob layer.

**Comment by optimumtact** [comment]
such solution, amazing, wow!
:+1:

**Comment by optimumtact** [comment]
I have a feeling it was probably so that mule bots appeared on top of the people they ran over, because that sounds like something old coders would do :smile:

**Comment by xxalpha** [comment]
No mulebots are actually on normal layers, it's just the smaller bots that are on layer 5.

**Comment by Razharas** [comment]
Oh god this is hilarious
5/5 now its not foam on the floor its a foam filling ht whole room

**Pull request merged**
