### PR TITLE
Revert "Revert "Removed anti-drop implant from NukeOps uplink.""

### PR DESCRIPTION
**Pull request by xxalpha**
Reverts tgstation/-tg-station#10887

No reason to revert this because you're offended I didn't state a very visible change. Implying I tried to sneak in changes in a 13 lines changed overall PR is ridiculous.

### CODE REVIEW

**Comment by Cheridan** [comment]
wake me up

**Comment by Thunder12345** [comment]
Wouldn't it be easier to have just stated all the changes the first time?

**Comment by xxalpha** [comment]
I am still not gonna state them because fuck you.

**Comment by Cheridan** [comment]
Please take this down a notch, guys.

**Comment by Thunder12345** [comment]
>I am still not gonna state them because fuck you.

Nice attitude there friend

**Comment by xxalpha** [comment]
>Why was it removed from the bundle?

So the bundle wouldn't be a shit buy. Even at 5TC, there was a good chance for the bundle to not pay for itself, since I removed one of the expensive implants. Removing it from the bundle assures that you always get at least it's price worth of items.

**Comment by Cheridan** [comment]
That sounds fine, since again hunger doesn't really matter for a nuke op. Frankly it could probably get taken out of the uplink altogether, it's just bloat.

**Comment by xxalpha** [comment]
Sure why not

**Comment by Lumipharon** [comment]
The nutriment implant is literally fucking useless to ops - why the fuck would they need it?
And by extension, why should anyone give a fuck how much it costs? Hell, it's probably a liability since those implant things react poorly to EMP's.

Seriously, no drops fuck nuke op balance, nutriment implants do nothing.

**Comment by SconesC** [comment]
>I am still not gonna state them because fuck you.
Whoa this is giving me mad flashbacks to that ban request

Why would nuke ops need this, since when has hunger EVER affected a nuke team? They even have a supply of donk pockets and a microwave on the shuttle.

**Pull request merged**
