### PR TITLE
Better sprites for chest cyber implants.

### PR DESCRIPTION
**Pull request by xxalpha**
implonts

At least it's not fruit. I am going to need the approval of  @Nienhaus or @WJohn.

### CODE REVIEW

**Comment by WJohn** [comment]
:+1: Why the hell was a fruit approved seriously.

**Comment by Nienhaus** [comment]
:+1:

**Comment by GunHog** [comment]
You know...because..Oranges...

**Comment by Fox-McCloud** [comment]
looks great! :+1:

**Comment by Iamgoofball** [comment]
:-1:

**Comment by AnonymousNow** [comment]
These look pretty good, I don't know why I see a thumb down up there.

**Comment by Iamgoofball** [comment]
i preferred the fruits

**Comment by AnonymousNow** [comment]
Okay.

We could make a vote thread on the forums.

**Pull request merged**
