### PR TITLE
[DNM] THE OWL RETURNS

### PR DESCRIPTION
**Pull request by dannno**
PART I:
- all owl items resprited
- owl wings added, wings toggleable

### CODE REVIEW

**Comment by CollenN** [comment]
This is amazingly awesome

:+1:

**Comment by Fox-McCloud** [comment]
the arms and the wings blend together when the wings are down.

**Comment by dannno** [comment]
I'm a little unsure what you mean
The wings are supposed to form a cloak and go around the front of the arms when down eg. http://static.comicvine.com/uploads/original/8/82281/1849101-owlman_1.jpg

**Comment by WJohn** [comment]
:+1: x :100: 
Considering how hideously AWFUL the original sprites are, I'm in love with these.

**Comment by AnonymousNow** [comment]
I support this. Nice to get some updated sprites that don't look like arse.

**Comment by WJohn** [comment]
Next is the monkey suit, which is arguably the most hideous suit in the whole entire game.

**Comment by dannno** [comment]
Consider it done

**Comment by Fox-McCloud** [comment]
I think just giving it a more defined edge on the wings and sleeves will alleviate the issues I'm talking about.

**Comment by Nienhaus** [comment]
I love this, but I also love the old suit. RIP Old owl. 2015 New Owl. :+1:

**Comment by paprka** [comment]
this is so fucking based i can't handle it

**Comment by dannno** [comment]
title updated to be in line with lore

**Comment by Mandurrrh** [comment]
I'm so glad you've recovered from the bread incident and came back swinging. Awesome.

**Comment by Czarcastic** [comment]
I kinda looked the cheesy look of the old costume. It makes you look like a guy in a silly costume rather than an actual superhero.

**Comment by WJohn** [comment]
The old sprite used the same front sprite as it did the back, no edits there. It's impressively terrible.

**Comment by Stickymayhem** [comment]
Can we have both?

One from cargo costume crates that looks good and one in the autodrobe that looks like the old shitty one?

I don't care that much but I always giggled at HoPs trying to be heros and looking like complete knobs.

**Comment by phil235** [comment]
:+1:

**Comment by Mandurrrh** [comment]
http://imgur.com/jsnuH4F

**Comment by Jalleo** [comment]
@danno villian suit for enemy of owlman when?

**Comment by RemieRichards** [comment]
:+1:

**Comment by Niknakflak** [comment]
These look amazing

**Comment by dannno** [comment]
@jalleo ;)

**Comment by ike709** [comment]
Make the suit spawn in the HoP's locker.

**Comment by dannno** [comment]
god no

**Comment by Dorsisdwarf** [comment]
The enemy of The Owl is any decent clown.

Nobody takes vigilantes seriously after ten straight minutes of being tabled and bikehorned while botany throws tomatoes at you.

**Comment by Chocobro** [comment]
hype. :+1:

**Comment by dannno** [comment]
I have no idea why but at some point in this PR I have turned every single jumpsuit in the game invisible. Not the SUIT error; completely invisible on-mob. When I pushed the last commit this was not the case, but I just reverted to it and it's happening and I am not sure why.

**Comment by dannno** [comment]
something dumb happened and I need to make a new PR because something dumb happened

**Pull request closed without merging**
