### PR TITLE
Cyber Implants + (Pt.2)

### PR DESCRIPTION
**Pull request by xxalpha**
- Fixed Nutriment implant printing.
- Added a remade Reviver implant: it now attempts to heal you back to consciousness if you pass out.
- Health Analyzers can now also detect cybernetic implants (like the MedHUD).

~~Added a cybernetic implant spawner to the NukeOps ship (spawns random number of random implants).~~
- Added cybernetic implants and a cybernetic implants bundle to the Nuke Ops uplink.
- X-Ray implant and Reviver Implant now require Biotech = 7. The only way to reach this level currently is by deconstructing two Alien Brains or by deconstructing one thermals implant and one alien brain(excluding the cases where you already have those implants).

--

Unrelated change: restored icon_states to all crates for the sake of mappers.

### CODE REVIEW

**Comment by GunHog** [comment]
That X-ray implant gating is a little extreme, is it not? Because of Genetics, it might as well not even exist now. As you have it, it is a forbidden fruit that will likely only ever be seen one round a month.

**Comment by xxalpha** [comment]
X-Ray can fuck over many game modes, so I think it's reasonable. It will still be randomly spawned for NukeOps.

It's something that I will probably keep tweaking, the lack of high level items makes this a tricky thing to balance.

**Comment by AlexCrimson** [comment]
http://pastebin.com/uidRcNg1

Its possible to get to Thermals with only miners help. There is a Syndicate toolbox on the mining asteroid which will get you illegal tech 2, TYRANT board for tech 3, then an Energy Crossbow for Tech 4.

So yeah, raising the super OP implants to bio 7 is the best option, as bio 6 is a very reachable goal for R&D.

Also you should totally give malf AIs the ability to temporarily assume direct control of people with cybernetic implants. Would be a good lategame ability for AI.

**Comment by xxalpha** [comment]
E-bows are buildable??

**Comment by AlexCrimson** [comment]
Yeah. They are big E-bows, not the mini ones.

**Comment by xxalpha** [comment]
Thanks for the feedback, @AlexCrimson. Increasing Thermals implant requirement so it's only obtainable if you get your hands on uplink items (hopefully for real this time).

**Comment by KorPhaeron** [comment]
Please don't put implants in the shuttle for free. Apparently e shields now reflect 100%. Someone who is laser/taser proof who also gets the anti stun implant will be more or less unkillable

**Comment by xxalpha** [comment]
Ion rifle in the armory.

**Comment by PKPenguin321** [comment]
a single hard counter in the armory where only a few people can access it and it can be blown up by nukeops if they enter through the armory =/= good

just make the implants be in the uplink and cost a decent amount of TC instead of being random and for free

**Comment by Lumipharon** [comment]
Kor, e-shields have literally always been 100% reflect, or atleast for the past 3 years.

**Comment by KorPhaeron** [comment]
My bad. I'll accept I have no idea what I'm talking about in regards to e shields since you guys apparently have gotten along fine with them.

Not a good thing to pair with no drop or antistun though. Also what PK penguin said.

**Comment by Lumipharon** [comment]
implants for ops would probably be bad because
A: They tend to be OP as fuck
B: Ops use emp's a lot. Assfucking your team mate because you didn't realise he had an implant would be pretty bad.

**Comment by palpatine213** [comment]
Laser pointer in eyes should dramatically fuck with eye implants, since it basically emps cameras and flashes borgs.

**Comment by ACCount14** [comment]
Just make syndie implants EMP-proof.

**Comment by xxalpha** [comment]
Gave Nuke Ops implants in their uplinks instead. Also gave them a box of implants:
implants

**Comment by PKPenguin321** [comment]
Implants and their TC values:
Thermal Vision Implant: 8
X-Ray Vision Implant: 10
CNS Rebooter Implant (Anti-Stun): 7
Anti-Drop Implant: 7
Reviver Implant: 8
Nutriment Pump Implant PLUS: 5
Cybernetic Implants Bundle (5 random implants): 25

Also unrelated but maybe change the Reviver Implant's name to the Revival Implant?

**Comment by Lumipharon** [comment]
That implant bundle is super cheap, considering even the shittiest implant on it's on is 5tc, and that 5/6 implants are good.

**Comment by KorPhaeron** [comment]
Implants break all the rules of ss13 ROBUST combat without any visual cue or downside, do ops really need them at all let alone so cheap? Doesn't add any new strategies or gameplay opportunities, just straight upgrades you jam into your character

In any case thanks for taking the random spawner out, I'm not going to agree on this so I'll leave the arguing to others.

**Comment by xxalpha** [comment]
Well the random spawner left it out of the control of the ops and prevented meta. And people have been telling me to give these to Nuke Ops and ERT and Death Squad so I am.

Saying the prices I set are too cheap is not specific and I won't act on it. I based them on other uplink item prices and I think they're okay.

**Comment by PKPenguin321** [comment]
>Saying the prices I set are too cheap is not specific

Well, for one thing, the CNS Rebooter is basically an infinite use automatic adrenal implant, and it costs 7 TC while the adrenal implant costs 8. Make it cost a *lot* more, like, 15 or something.

The bundle's really nice but a little too profitable, as you'll 9 times out of 10 get more than what you payed. Either bump it up to about 40 or make some of the better implants restricted from it (like the rebooter and xray).

I'd bump nodrop up to at least 8 considering it has arguably more utility than other items. Reviver, nutriment, xray, and thermals all seem fine.

I have a lot of hope for this PR.

**Comment by GunHog** [comment]
Merge now?

**Comment by KorPhaeron** [comment]
@Gunhog 

Nuke op win rate is almost exactly 50% right now I still don't think they need to be able to buy what is essentially stun immunity

**Comment by GunHog** [comment]
Where do you get those stats? And have Alpha remove it from the uplink in that case.

**Comment by KorPhaeron** [comment]
http://ss13.eu/tgdb/tg/latest_stats.html#mode_nuclear_emergency

Most of those losses are probably due to awful play on the part of the ops in question as well, not because of their lack of good gear. 5 people are consistently beating the other 60 on the server.

**Comment by Razharas** [comment]
This is why having fixes and balance changes in one pr is bad

**Comment by xxalpha** [comment]
This is why leaving a PR open for 2 months is bad.

**Comment by Razharas** [comment]
Ok since this is clearly abandoned by everyone i make a judgement call - good design
At least cries for revert will draw attention to this

**Comment by KorPhaeron** [comment]
@razharas

An infinite, more or less undetectable buff that invalidates the basis of the combat system (stuns), is not good design

Giving it to an antag that already has a 50% chance of killing the server is not good design.

Making the only counter to item something that only said antags have reliable access to is not good design

Which part do you find well designed?

**Comment by freerealestate** [comment]
WOO

**Pull request merged**
