### PR TITLE
Adds EMP mode to Stun baton.

### PR DESCRIPTION
**Pull request by xxalpha**
Stun baton with an EMP mode. Attacking someone with a baton set to EMP will EMP everything in target's contents.

### CODE REVIEW

**Comment by francinum** [comment]
@xxalpha why?

**Comment by PKPenguin321** [comment]
incoming controversy

**Comment by ACCount12** [comment]
Stun baton is already OP. And now you can shut down your victim's radio in one hit with it, without any traitorous items.
:-1:

**Comment by SconesC** [comment]
This is a joke PR right

**Comment by Dicks1** [comment]
Just under a week until april fools

**Comment by Lumipharon** [comment]
You squidin' me?

**Comment by xxalpha** [comment]
@Account12 Don't lose the baton then.

**Comment by Dorsisdwarf** [comment]
Consider use & power with borgs. 

Does this EMP cameras?

Does this EMP fire alarms?

Does this EMP doors?

Does this EMP carried defibrilators?

----------------------------------------------------------------

Additionally, I'm assuming the point of this is to empty all the weapons in someone's inventory. Seeing as antags generally have bullet weaponry, what is the intended legitimate use of this?

**Comment by xxalpha** [comment]
More EMPs.

**Comment by Xhuis** [comment]
Rip borgs
Rip cameras
Rip thermals
Rip doors
Rip laser/energy/taser guns
Rip radios

:-1:

More EMPs is not a valid reason for this. More EMPs isn't inherently a bad idea, but it definitely is with this implementation.

**Comment by Steelpoint** [comment]
Too powerful for a very common item.

:-1:

**Comment by dannno** [comment]
what were you thinking
really, what were you thinking?
:-1:

**Comment by pudl** [comment]
are you actually retarded :-1:

**Comment by xxalpha** [comment]
@dannno I was thinking "wow this took zero effort to do, maybe I should push it". You don't have to be offended.

**Comment by dannno** [comment]
lol i'm not
but now that you singled me out i am :(

**Comment by Cheridan** [comment]
What.

Yeah, this isn't a very good idea.

**Comment by GunHog** [comment]
Use your Ion Rifle in the armory, or pester Science for a carbine. You could even help them max their combat tech so you can have it loyalty pinned.

**Comment by hornygranny** [comment]
this is a terrible idea

**Pull request closed without merging**
