### PR TITLE
PROPER SLURRING

### PR DESCRIPTION
**Pull request by dannno**
Let me know if I missed anything.

### CODE REVIEW

**Comment by hornygranny** [comment]
show the results on a lizardman please

**Comment by WJohn** [comment]
How does this work with being stunned, or lizards, or being a stunned lizard?

**Comment by xxalpha** [comment]
>How does this work with being stunned, or lizards, or being a stunned lizard?
They ssssssssslur, of course.

:+1:

**Comment by dannno** [comment]
Johnny Phillips slurs, "SssssslIppppIn sschusSSAN hooT SsSaaaschCHchschAHFRah'chschsss"

lizard is fine

You feel a powerful shock coursing through your body!
Jane West stammers, "F-fooc-kk'-K"
Jane West stammers, "Ooh-h' gg---gOd'"
Jane West slurs, "It...huuuhhh...huRTssss"

stunned lizards are fine unless you're a NITPICKER

**Comment by pudl** [comment]
bay slurring is terrible with its ''''''''''s and aLtErNaTiNg cApS

**Comment by RandomMarine** [comment]
Better than obnoxious stuttering by a long shot, pudl.

**Comment by dannno** [comment]
merge

**Pull request merged**
