### PR TITLE
Removes the Clown, Who needs that guy anyways?

### PR DESCRIPTION
**Pull request by KingOfConflict**
guys think about it, what does the clown actually do besides honk and shit up the station with shitty dumb jokes, this is a plasma research station not a standup comedy.

### CODE REVIEW

**Comment by Xhuis** [comment]
Aranclanos approved

**Comment by Aranclanos** [comment]
no troll prs please

**Comment by KingOfConflict** [comment]
wowwwww what is this fucking shit, this is a serious pr

**Comment by Incoming5643** [comment]
Guys come on we only have so many numbers here

**Comment by Chocobro** [comment]
hi xhuis

**Comment by KingOfConflict** [comment]
okay so can i pr bomb vests or are you guys anti-fun.

**Comment by ninjacha** [comment]
Awww, nerd beat me to it.

**Comment by ninjacha** [comment]
RIP

**Pull request closed without merging**
