### PR TITLE
Removed /proc/is_hot() && Removed /proc/is_sharp()

### PR DESCRIPTION
**Pull request by xxalpha**
Added /obj/item/proc/is_hot()
Added /obj/item/proc/is_sharp()

### CODE REVIEW

**Comment by Anonus** [comment]
MORE LINES REMOVED THAN ADDED :+1:

**Comment by xxalpha** [comment]
Added lines are inflated because I had to rename a var with a conflicting name.

**Comment by Razharas** [comment]
Please do the same with sharp

**Comment by Razharas** [comment]
ALso the perfect way would be to add a stat flag ON that would mean the item is in active state, be it lit candle or active esword
That would make things use the stat and place all the code into the highest parent

**Comment by xxalpha** [comment]
I disagree, I think this is the perfect way, it offers flexibility. Some items don't have on or off states.

**Comment by Razharas** [comment]
Real nice

**Pull request merged**
