### PR TITLE
Fixed cables floating in space after RCD decon.

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/7934

### CODE REVIEW

**Comment by MrStonedOne** [comment]
to be honest, I don't mind this that much.

it makes sense for the cable to remind, but not be placable in space.

**Comment by xxalpha** [comment]
You can't place them in space though. It's not like pipes which you can secure in space.

Either this is merged or the issue report closed and considered a feature.

**Comment by Lumipharon** [comment]
I don't actually see any reason that a cable shouldn't be able to float in space.
The only reason it wouldn't, would be if the cable was anchoring a chunk of the station, but turfs don't move anyway so...

**Comment by ExplosiveCrate** [comment]
I kinda like the thought of cables sort of floating haphazardly in space after a careless renovation/construction and sort of wish there was a way to do it legitimately without having to resort to abusing a bug.

**Comment by Aranclanos** [comment]
I don't think these kind of checks should exist in RCD code, any other cases of floors changing to space can find the same results

**Comment by xxalpha** [comment]
Wouldn't those cases destroy the cable?

**Comment by Aranclanos** [comment]
I guuuuuuesss

**Comment by blobbernaut** [comment]
no, this isn't needed. Malf ais can deconstruct their floors with an engi borg for added defense so there's that to consider

**Comment by Aranclanos** [comment]
its not like the cables cover the entire room

**Pull request merged**
