### PR TITLE
Fixes away mission icon smoothing.

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/13476

Issue only affects turfs and happens only because something something map loader.

### CODE REVIEW

**Comment by Aranclanos** [comment]
why does that spawn even exist again

**Comment by MrStonedOne** [comment]
because shit breaks if it doesn't

**Comment by tkdrg** [comment]
@Aranclanos
I was stumped about that when I refactored turfs, as well. From what I understood, when a map gets instanced, it will load turfs simultaneously, so that turf smoothing without a delay just won't smooth at all (despite working if you break/rebuild it later in the game). The same is true for stuff like putting items on top of closets on the map, if you don't delay it they will not get put inside the closet by its New(). A spawn(1) is the shortest solution to that (considering we can't change byond's map loader), though making a turf/initialize() and calling that on SSobject is another very suitable possibility (I'm not sure if the map loader calls initialize(), however).

**Comment by MrStonedOne** [comment]
you could make it faster by doing

`set waitfor = 0` at the top of the proc then using a sleep instead of a spawn

**Comment by xxalpha** [comment]
Changed it according to mso's suggestion.

**Comment by MrStonedOne** [comment]
nvm, it's only faster when you have spawns and sleeps, just a spawn(1) with no sleeps is faster then set waitfor = 0; sleep 1

**Comment by WJohn** [comment]
Also welcome back, haven't seen you in a month.

**Pull request merged**
