### PR TITLE
Fix autolathe rejecting stacks.

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/11771

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
@WJohn 

Should probably be high priority, as this bug effectively removes autolathes from being used, entirely.

**Comment by Fox-McCloud** [comment]
@WJohn

Should probably be high priority, as this bug effectively removes autolathes from being used, entirely.

**Comment by GunHog** [comment]
Well, not ENTIRELY. A workaround would be to insert non-stack items. Very inefficient, but it will work for now.

**Comment by Lumipharon** [comment]
Please speed merge. Can't murder bone when I can't print ammoboxes.

**Pull request merged**
