### PR TITLE
Doubled security cyborg module health, from 100 to 200.

### PR DESCRIPTION
**Pull request by xxalpha**
The combat cyborg shouldn't be as fragile as the other modules.

### CODE REVIEW

**Comment by Anonus** [comment]
WHAT A MEME

**Comment by Fox-McCloud** [comment]
Absolutely nuts.

**Comment by Ergovisavi** [comment]
:-1: 
Stop being retarded.

**Comment by Iamgoofball** [comment]
posting in a meme ;PR

**Comment by MMMiracles** [comment]
the ride never ends

**Comment by SconesC** [comment]
meme pr off the port bow captain elevate to red alert and prepare to be memed

**Comment by bgobandit** [comment]
I am the honkman
we are the honkmen

**Comment by Aloraydrel** [comment]
I love this meme so much I am promoting it to top meme

**Comment by Cebasiz** [comment]
i play secborg all the time and i'm not sure this is wise

**Comment by TechnoAlchemisto** [comment]
Peak hilarity

**Comment by Shapsy** [comment]
can we give them a flashbang launcher and also make it immune to flashbangs

**Comment by daman997** [comment]
p l s
:-1:

**Comment by PKPenguin321** [comment]
>makes extremely unpopular PR that buffs secborgs, gets shouted at
>makes another one that's even crazier almost immediately afterwords
:-1:, ban from github when?

**Comment by Iamgoofball** [comment]
>banning from github because a change is not 100% agreed with

literally autistic

**Comment by PKPenguin321** [comment]
the guy who shat up a thousand stunglove meme prs got banned, and these prs are arguably worse

**Comment by Niknakflak** [comment]
:-1:

**Comment by SconesC** [comment]
@PKPenguin321 Yeah but he got told to stop by maintainers multiple times and was a general shitter in IRC

**Comment by Xhuis** [comment]
### ___NO.___
thumbsdown

**Comment by kevinz000** [comment]
Do it

**Comment by Jalleo** [comment]
Can this sec borg code war please stop its better as the status quo

**Comment by Dorsisdwarf** [comment]
@PKPenguin321 

Reminder that MSO tried to change Github's Open Community Guidelines by spamming the same PR and issue twenty times.

**Comment by Miauw62** [comment]
niceme.me

**Pull request closed without merging**
