### PR TITLE
Reskin/Rename Double Barrel Shotgun

### PR DESCRIPTION
**Pull request by dannno**
port from NT

### CODE REVIEW

**Comment by Cheridan** [comment]
#3167 The old PR for reference.

**Comment by dannno** [comment]
oh, I didn't know that existed

**Comment by paprka** [comment]
>aranclanos closed it

wow, it's fucking nothing

**Comment by WJohn** [comment]
Woah woah woah now, we can have *different types of wood?*

:+1:

**Comment by Lumipharon** [comment]
Literally 3rd best feature from NT.

**Comment by dannno** [comment]
merge?

**Comment by optimumtact** [comment]
>still using a verb

Did you even read the comments left by aranclanos, or are you just dense

**Comment by dannno** [comment]
The detective revolver works the exact same way. It's a fine way to do it. If you want to find a better way, feel free.

**Comment by dannno** [comment]
ps. merg

**Comment by Jordie0608** [comment]
Changelog

**Comment by dannno** [comment]
changes logged

**Comment by dannno** [comment]
meeerrrrrrgggggggggggg

**Comment by paprka** [comment]
you tested this with all the colors and sawing off right?

**Comment by dannno** [comment]
yup, triple checked

**Comment by hornygranny** [comment]
not with an object verb. make the shotgun spawn on the bartender, and then give him choices to name and sprite it, like the chaplain gets

**Comment by dannno** [comment]
gross
the detective revolver works exactly like this

**Comment by dannno** [comment]
so am I really gonna have to change this when the detective's works the exact same way
if so i probably won't do it soon

**Comment by paprka** [comment]
*shrug, just because an old system is crap doesn't mean yours should be crap. I suggest replacing the rename verbs for the detective and shotgun with simply hitting it with a pen, and the reskin as a roundstart thing.

**Comment by dannno** [comment]
then i'll do this some time later

**Comment by Chocobro** [comment]
requesting bread colours

**Pull request closed without merging**
