### PR TITLE
Divide beach coast icon into two.

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/5325

### CODE REVIEW

**Comment by tkdrg** [comment]
Why is this needed?

**Comment by xxalpha** [comment]
because byond is bad

**Comment by duncathan** [comment]
Big icons a shit

**Comment by tkdrg** [comment]
Yes thank you for the clear explanation I understand nothing

**Comment by xxalpha** [comment]
I don't know how I can explain it better than the referred issue.

**Pull request merged**
