### PR TITLE
buffs snpc swearing

### PR DESCRIPTION
**Pull request by hornygranny**

### CODE REVIEW

**Comment by Archie700** [comment]
What

**Comment by Zilenan91** [comment]
You know how automaton SNPCs scream random shit that usually involves greytiding, shitcurity, that kind of thing? This adds more words so that their phrases are more varied.

**Comment by Archie700** [comment]
I know what is happening. I want to know why we're making them more obnoxious than they already are

**Comment by KazeEspada** [comment]
Fuck your shit cock you cuck cunt.

**Comment by PKPenguin321** [comment]
:ok_hand:

**Comment by hornygranny** [comment]
😂:ok_hand:

**Comment by PKPenguin321** [comment]
that is probably the most appropriate use of the fuck tag we've ever had

**Comment by Aloraydrel** [comment]
im gonna cuck you right in the face! Just you wait!

**Comment by bgobandit** [comment]
man eat a dong

**Comment by Niknakflak** [comment]
He added swear words that americans use but americans do not say wanker.

**Comment by Shadowlight213** [comment]
Not family friendly. I feel some may be triggered by this addition.

**Comment by Iamgoofball** [comment]
@Niknakflak a real swear artist uses all dictionaries

**Comment by bgobandit** [comment]
@niknakflak stop being a wanker

**Comment by F-OS** [comment]
@Shadowlight213 9. Players need to be above the age of 18.
    This is due to the adult game content and the local laws of where our server is based.

**Comment by Shadowlight213** [comment]
@F-OS
You don't need to be under 18 to be triggered. Honk.

**Comment by Archie700** [comment]
>Honk

Triggered

**Comment by Bawhoppen** [comment]
we need more than just these come on hg why did you stop trying

**Comment by duncathan** [comment]
we all know everyone on the server is 18

**Comment by Cheridan** [comment]
broke by uhh uhhhh #15712

**Pull request closed without merging**
