### PR TITLE
Added maintenance glass airlock and external glass airlock.

### PR DESCRIPTION
**Pull request by xxalpha**
Not adding these to any map, just two airlock types mappers can use.

itjustwerks

### CODE REVIEW

**Comment by WJohn** [comment]
Neat.

**Comment by Shadowlight213** [comment]
:+1:

**Comment by GunHog** [comment]
Ossim.

**Comment by swankcookie** [comment]
:+1:

**Comment by Bawhoppen** [comment]
First we'll take their code
Then we'll take their RP
(and everyone will be really really happy again :smiley_cat:

**Comment by xxalpha** [comment]
WHAT?

**Comment by Shadowlight213** [comment]
The fuck? What are you implying bawhoppen?

**Comment by Bawhoppen** [comment]
bay

**Comment by xxalpha** [comment]
Are you saying bay will take our RP? Why would bay do that?

**Comment by Bawhoppen** [comment]
>we'll
>their

**Comment by xxalpha** [comment]
I am still not sure what you are implying.

**Comment by duncathan** [comment]
What does this have to do with bay code???

**Comment by Bawhoppen** [comment]
nevermind, it doesn't matter

**Comment by Shadowlight213** [comment]
@xxxalpha I'm guessing bawhoppen is implying you stole the sprites from baycode

**Comment by Bawhoppen** [comment]
no but its similar looking to something on one of those fancy codebases so thats why i even brought it up

**Comment by swankcookie** [comment]
It's kinda shitty to imply that something is stolen if you have know idea whether it actually was.  Spriting can be a fucking pain.

**Comment by Bawhoppen** [comment]
I never said it was stolen or implied that, I was just saying this is the kind of thing you would notice feature difference you notice when you go to one of those servers with their fancy shit

**Comment by xxalpha** [comment]
We fancy shit too, occasionally. Work was put into being able to create these glass airlocks effortlessly, I am no spriter.

**Comment by tkdrg** [comment]
Just to make sure, what's up with the sprites here? Do they look too similar to another server's or what?

**Comment by Jordie0608** [comment]
@tkdrg Sprites are fine, just a miscommunication

**Pull request merged**
