### PR TITLE
Fixes covering clothing not hiding gender on examine()

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/4833

### CODE REVIEW

**Comment by Arquebusier** [comment]
memetic

**Comment by Zilenan91** [comment]
Just put it all to he rather than feminism memes, hardsuits look like they're built for dudes.

**Comment by Arquebusier** [comment]
Someone didn't read the PR

**Comment by GunHog** [comment]
I was triggered by this as well, but I learned my lesson the last time someone put in a troll PR name.

**Comment by phil235** [comment]
Title must be an accurate description of the PR.

**Comment by xxalpha** [comment]
I wasn't aware this codebase banned memes, but alright.

**Comment by duncathan** [comment]
We don't like click bait

**Pull request merged**
