### PR TITLE
Fix syndicate briefcase not having cash.

### PR DESCRIPTION
**Pull request by xxalpha**
:moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
It had cash in it yesterday when I rolled antag and bought 20 briefcases and bribed the grey tide

**Comment by xxalpha** [comment]
You sure? I tested it twice with fresh versions and none had cash.

**Comment by Dorsisdwarf** [comment]
Yeah, it sorta caused the everything to descend into chaos, the HOS bursting into the courtroom with wads of money and demanding the trial be stopped, briefcase smacking assistants smashing down windows to space, that kind of thing

**Comment by xxalpha** [comment]
I'll test it more tonight. You're referring to the syndicate briefcase bought with 1TC, right?

**Comment by Profakos** [comment]
I have had this issue on another server, it only lacked money if it spawns in your hand, and you open it without putting it down first. The money appeared if you put it down and picked it up again. Could have been a different bug though.

**Comment by xxalpha** [comment]
That may explain it, in which case, this fix is valid.

**Comment by xxalpha** [comment]
The bug is triggered by trying to open the briefcase while it's locked, the contents are deleted with a simple click before unlocking a first time. This PR fixes that.

**Pull request merged**
