### PR TITLE
Lots of AI core sprites

### PR DESCRIPTION
**Pull request by dannno**
for fun

I'm too lazy to make gifs of every new sprite
they're all pretty cool
credit goes to the respective people who made them

### CODE REVIEW

**Comment by TheVekter** [comment]
:+1: Very nice.

**Comment by tkdrg** [comment]
Not sure what the copyright policy has to say about these, but I like them.

**Comment by paprka** [comment]
Why do we have so many AI cores when they're almost never changed from the default

**Comment by dannno** [comment]
for fun

**Comment by WJohn** [comment]
Holy shit that alien AI core sprite I drew from FOREVER ago is in there? I'll probably end up redoing that at some point as it's horribly ugly and outdated.

**Comment by dannno** [comment]
>Like syndicatmeow, helios, and hades are all players that don't play anymore

helios isn't a player ref

the other two are still decent sprites so like who cares

**Comment by Steelpoint** [comment]
Don't forget there's a human brain inside the AI Core. Just don't tell anyone, its very hush hush.

All of these are good sprites in my opinion, and variety is good.

**Comment by GunHog** [comment]
There are some good ones in there, indeed. :+1: I would personally like to see more AI status screens about the station and more options for them, but more cores are nice too.

**Comment by Anonus** [comment]
:+1: 
Includes a variety of crewmember cameos.

**Comment by Niknakflak** [comment]
Don't forget that AIs can have specific death sprites.  A feature I added in a PR (but like everyone else coded because I can't into code).  Allows you to take a sprite of an AI and add  _death (or _dead, I don't remember specifically, just look in the file) at the end for the sprite to go to that specific dead sprite instead of standard blue screen.  Only two cores use the function right now, I think.  Might be cool to add some to this PR.

**Comment by Niknakflak** [comment]
Database AI core could have "Database error" screen come up or something for example.

**Comment by Niknakflak** [comment]
Shit the image just loaded on my phone.  Well that image speaks for itself.

**Comment by Steelpoint** [comment]
if I'm not mistaken but that's the case for many of the sprites in this PR.

**Comment by Niknakflak** [comment]
More AI death cores could be added too.  That would be cool.

**Comment by Miauw62** [comment]
>ai-gentoo

fuck yes

**Comment by Cheridan** [comment]
Gigyas and e102 are obvious violators of our no-copyright policy. Yuki's probably from some dumb anime and should get removed too if that's the case.

ai-smiley looks terrible and completely inconsistent with the rest of the game.

**Comment by dannno** [comment]
I kind of forgot about the policy, will remove

**Comment by paprka** [comment]
Alterego is from that one sameface shitty VN tier 'game'

**Comment by dannno** [comment]
you're a fucking snitch paprika

**Comment by paprka** [comment]
>liking horrible shitganronpa garbo

you deserve it

**Comment by dannno** [comment]
I hate dangon ronpa tho
but that AI is kawaii and you know it

**Comment by TZK13** [comment]
Was the Yuki one actually from an anime or are we just guessing? The thread where it was posted on Erro's old forum doesn't say.

**Comment by Miauw62** [comment]
www.youtube.com/watch?v=NI_fgwbmJg0

**Comment by tkdrg** [comment]
Matrix is probably copyrighted too but at this point I don't think anybody cares.

**Comment by hornygranny** [comment]
:cop: :e-mail: :arrow_right:

**Comment by hornygranny** [comment]
also please make a :^) ai sprite

**Comment by TheVekter** [comment]
I have trouble believing we would get a DMCA over a 20x20 gif but okay

**Comment by dannno** [comment]
yeah me too but what're ya gonn dooooo

**Comment by paprka** [comment]
Remove anime

**Comment by hornygranny** [comment]
yes, no external references

**Comment by dannno** [comment]
All that stuff was removed like I said
so it's good to go

**Comment by hornygranny** [comment]
can you show the new list pls

**Comment by dannno** [comment]
it's the same thing minus yuki, gigyas, alter ego, smiley, and e102.

**Comment by dannno** [comment]
so merge?

**Comment by TZK13** [comment]
>Maintainers getting blustered over video game and anime references, literally allows a copyrighted photo.

:^)

**Comment by paprka** [comment]
which one?

**Comment by TZK13** [comment]
Bliss.

**Comment by Regen1** [comment]
Pretty sure these are from paradise by the way, considering the Yuki "anime" one was made to me by request from Wisewill.

At least give credit where credit is due

**Comment by dannno** [comment]
Yuki isn't in the PR anymore

**Comment by Regen1** [comment]
I actually wonder who made the dead yuki sprite, Wisewill never made one as far as I am aware

**Comment by dannno** [comment]
I might have made that for NT a long time ago but I can't remember for sure

**Comment by TZK13** [comment]
Regardless Yuki wasn't taken from Paradise considering wisewill freely distributed them on the old /tg/station forums without asking that people give credit to Paradise: http://wildhogs.canadian-pharmacy.us/phpbb/viewtopic.php?f=11&t=3250

If you are the one that asked for Yuki to be made though is there actually any source for it? It doesn't really look like yandere Yuki to me very much considering the difference in hair length.

**Comment by RemieRichards** [comment]
@TZK13 it doesn't really look like Yuki at all because it's Yuno, it's a joke.

**Comment by Regen1** [comment]
@TZK13 http://80.244.78.90/phpBB3/viewtopic.php?f=2&t=440&sid=0087c7afe953d7e83f88296a7dc7e13a&start=10 is where he first posted it by request from me, however applogies for not realizing he posted them elsewhere as well, that one is on me.

and sidenote, it's yuki from the melanchollies of haruhi suzumiya, not Mirrai nikki

**Pull request merged**
