### PR TITLE
Removes Santa Hats from security wardrobe closets and the festivus pole from RD's office.

### PR DESCRIPTION
**Pull request by xxalpha**
Resolves https://github.com/tgstation/-tg-station/issues/8053.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:

**Comment by WJohn** [comment]
Come on, it's nearly march. This had to happen sooner or later.

**Comment by bgobandit** [comment]
grinch confirmed

**Comment by Nienhaus** [comment]
:-1:

**Comment by paprka** [comment]
I thought i already removed these

**Comment by Steelpoint** [comment]
This is good :+1:

**Comment by Iamgoofball** [comment]
@Steelpoint get on #coderbus

**Comment by Steelpoint** [comment]
W-why?

**Comment by Iamgoofball** [comment]
i need to talk wiki with you

**Comment by MrPerson** [comment]
[grinching intensifies]

**Pull request merged**
