### PR TITLE
Fixed not being able to eat with adjusted masks.

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/10205

### CODE REVIEW

**Comment by PKPenguin321** [comment]
does this fix the welding mask wonkiness too

**Comment by phil235** [comment]
You forgot that visor_flags does not contain only cover stuff but also HIDEFACE for example, which needs to be added to flags instead of cover_flags.

**Comment by xxalpha** [comment]
Right. This is shit code.

**Comment by xxalpha** [comment]
Alright this should have everything working.

**Comment by phil235** [comment]
This fix prevents masks and headgears from having any cover flag while adjusted, but I can't think of a better solution and right now no mask or headgear uses this possibility so meh.

**Pull request merged**
