### PR TITLE
Made it possible to emag a cyborg more than once.

### PR DESCRIPTION
**Pull request by xxalpha**

### CODE REVIEW

**Comment by GunHog** [comment]
Why?

**Comment by RemieRichards** [comment]
:-1: No, this is stupid, You're going to have emagged cyborgs get the message about laws being updated to being a syndicate borg, admins are going to be needlessly messaged again, etc.
It's worthless.

**Comment by xxalpha** [comment]
>muh messages

This is so you can "steal" cyborgs from other traitors.

**Comment by GunHog** [comment]
@WJohn I recommend you put a "Feature" or "Balance" label, not "Fix" here. It is not a fix, as it was never intended for borgs to be emagged more than once.

@xxalpha re-write the code so that it supports 'stealing' borgs that are already emagged, and make it clear that is what is happening.

**Comment by xxalpha** [comment]
"You emagged cyborg" is clear enough. Also a law update will be clear for the cyborg.

**Comment by Miauw62** [comment]
Yeah this will result in great situations :+1:
Op 24-jul.-2015 14:22 schreef "xxalpha" <notifications@github.com>:

**Comment by Anonus** [comment]
I'd suggest having it add the emagger to the laws instead.

**Comment by JJRcop** [comment]
I'm with @GunHog

**Comment by SconesC** [comment]
I don't see an issue with it

Emagging an already emagged borg to make it YOUR emagged borg sounds fun

**Comment by xxalpha** [comment]
>I'd suggest having it add the emagger to the laws instead.

You have to assume there will be a conflict of interests between the two emagging traitors.

**Comment by Anonus** [comment]
It's more fun not to, as the borg desperately tries to keep both alive and not shooting each other.

**Comment by Cebasiz** [comment]
might be cool to just have it add the new 'magger's name to the zeroth law assigning who is a syndicate agent

then you could introduce them and they could be best friends forever.. or immediately start a shootout.

**Comment by Shadowlight213** [comment]
:-1: I don't like it. There already was an issue with traitor borgs getting fucked over by someone with an emag if they hadn't hacked themselves yet. Now traitor Ais, who are already pretty much fucked if they have no borgs, can have their borgs stolen from them with no way of getting them back.

**Comment by Dorsisdwarf** [comment]
Solution: Let traitor AIs remotely hack borgs. Helps with the "make an unsynced borg to instakill" method too

**Comment by SconesC** [comment]
godmode silicons dont need buffs

**Comment by GunHog** [comment]
An easier fix would be to protect borgs linked to a Traitor AI from things that clear its zeroth law.

**Comment by Aranclanos** [comment]
I wonder how many times someone tried to emag an already emagged borg in the history of the game

**Comment by xxalpha** [comment]
Why do you think I made this PR?

**Comment by Miauw62** [comment]
i ded pls nerf

**Comment by bustygoku** [comment]
>i ded pls nerf

If you're enough of a scumbag to try emagging borgs to complete your objectives for you like an unrobust noob, you deserve it to blow up in your face.

**Comment by xxalpha** [comment]
And you're a faggot.

**Comment by CorruptComputer** [comment]
>And you're a faggot.

**Comment by Aranclanos** [comment]
great posts guys

**Comment by phil235** [comment]
:-1: This needs a check to prevent the same user to emag a borg repeatedly which would spam admins. You also need to resolve the issue with traitor AIs losing their borgs to other traitors.

**Comment by Razharas** [comment]
@xxalpha

**Comment by Razharas** [comment]
Nice

**Pull request merged**
