### PR TITLE
to be totally honest if someone had like a fuzzy condom or something i would not mind a dick in my ass right now

### PR DESCRIPTION
**Pull request by doubledankmemes**
dank memes

### CODE REVIEW

**Comment by Arquebusier** [comment]
Format fail

**Comment by TechnoAlchemisto** [comment]
open source was a mistake

**Comment by Anonmare** [comment]
Let's not.

**Comment by Bawhoppen** [comment]
FREEDOM!!!!

**Comment by TheColdTurtle** [comment]
remove

**Comment by TheColdTurtle** [comment]
OOC: IcePacks: to be totally honest if someone had like a fuzzy condom or something i would not mind a dick in my ass right now

**Comment by okaw** [comment]
HYELP

**Comment by fonedsky** [comment]
stop the memes

**Comment by Aloraydrel** [comment]
this is a bad meme

**Comment by okaw** [comment]
based cheri

**Comment by Bawhoppen** [comment]
:orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book: :orange_book:

**Pull request closed without merging**
