### PR TITLE
Fixed departmentental security spawning.

### PR DESCRIPTION
**Pull request by xxalpha**
Added departmental security spawn points (landmarks). In the absence of spawn points, the security officers will spawn in the department's security office area (as it worked before).

Removed check that was making it impossible for officers to be teleported to their respective department security offices.

Fixes https://github.com/tgstation/-tg-station/issues/2707

### CODE REVIEW

**Comment by Xhuis** [comment]
confliqutes

**Comment by xxalpha** [comment]
No shit.

**Comment by WJohn** [comment]
You forgot the map merger :p

**Comment by xxalpha** [comment]
I should be last in line for the map edit, so I didn't bother fixing up the map yet.

**Comment by Miauw62** [comment]
just use the map merger man it makes everything much neater.

**Comment by xxalpha** [comment]
Added spawn points to both Box and Meta.

**Pull request merged**
