### PR TITLE
Redo space suit storage, repath gas tanks

### PR DESCRIPTION
**Pull request by xxalpha**
-Hardsuits can now hold those big tanks again.
-Repaths gas tanks to 'large' gas tanks.
-Repaths hardsuits.
-Hardsuits can't hold jetpacks.

Update:
-All space suits can hold the same basic items (flashlights, large gas tanks, emergency gas tanks)

### CODE REVIEW

**Comment by Atskadan** [comment]
power creep would imply they havent always been that way

**Comment by paprka** [comment]
Contain your newfaggotry, please.

**Comment by Atskadan** [comment]
unless youre going to go with the epic "i used another ckey" excuse i've been playing way longer than you
and i don't think having armor on the suits is a bad thing. people abusing it indoors are slow as fuck and can still be dealt with by just stunning them and stripping them, which is easier to do because as mentioned they are slow as fuck.

**Comment by paprka** [comment]
Hardsuits have ridiculously long strip timers, and if the solution to armor being unbalanced is to 'just strip the armor' when engineers shouldn't have armor in the first place you simply have no idea how game design works. Engineers used to use space suits, not hardsuit, until someone got a dead space boner.

**Comment by Atskadan** [comment]
you didnt address the fact that wearing it inside (and outside too honestly) makes you a slow as fuck easy target for any type of disabling
plus if the strip time is an issue, just make it shorter
it's not unbalanced if it has huge glaring weaknesses like that

**Comment by optimumtact** [comment]
Please take this discussion to the forum since it's now at most tangential to the original PR

**Comment by paprka** [comment]
The way it relates to the PR is the fact that people say that hardsuits should be unique and hold large tanks only, but they're almost identical to regular space suits, so no they shouldn't because it makes this shit inconsistent like it was before. The difference between hardsuits and space suits is the fact that they have head lamps and special armoring, that's it, they aren't uber advanced.

**Comment by Steelpoint** [comment]
Is this being worked on still?

**Comment by xxalpha** [comment]
It's worked on, I'll have it merged or closed by the end of the day.

**Comment by paprka** [comment]
Yeah just fix this so it can be merged, I'm sick of the bickering. If this is really the only way people are using large tanks (I put them on my back or in a free hand) then it should be merged for 'quality of life' alone.

**Comment by xxalpha** [comment]
That's fixed, thanks.

**Comment by Miauw62** [comment]
isn't it easier to make a new PR?

**Pull request closed without merging**
