### PR TITLE
removes roundstart paladin and robocop boards

### PR DESCRIPTION
**Pull request by hornygranny**

### CODE REVIEW

**Comment by Anonmare** [comment]
:+1:

**Comment by Aloraydrel** [comment]
ADIOS VALID BOARDS

**Comment by Iamgoofball** [comment]
>>>CONFLICTING WITH MY 2 MILLION CHANGED LINES

**Comment by MrPerson** [comment]
I'm just going to repeat the exact same thing I said in IRC:

There's no point removing these if freeforms are still available since freeforms can do the exact same thing.

That being said, fuck robocop. Paladin needs rewriting at the very least and even then would still probably suck.

**Comment by Core0verload** [comment]
:-1: If Paladin is only ever used as excuse to make AI validhunt, there is something wrong with players, not with boards.

**Comment by Cheridan** [comment]
https://github.com/tgstation/-tg-station/pull/12589/files

**Comment by xxalpha** [comment]
:+1:

**Comment by PKPenguin321** [comment]
:+1:

**Comment by Ultimate-Chimera** [comment]
:+1:

**Comment by Cebasiz** [comment]
paladin should be left in

it's a redeemable lawset, it just needs actual admin enforcement and player knowledge of what you are supposed to do tbh

**Comment by Bawhoppen** [comment]
paladin is an awful lawset quite frankly

**Comment by Cebasiz** [comment]
what's wrong with it

**Comment by Bawhoppen** [comment]
it's used in the most retarded way and since it's so vague it can't be argued with

**Comment by Cebasiz** [comment]
fair

**Comment by KorPhaeron** [comment]
Read my mind. Was going to do this when I got home.

**Pull request merged**
