### PR TITLE
Simplified nuke deconstruction, removed nuke radiation.

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/10632
Partially addresses https://github.com/tgstation/-tg-station/issues/10876
Renders https://github.com/tgstation/-tg-station/pull/10903 useless if merged

 - Nuke deconstruction reduced to three steps with standard tools (no more special tools)
 - Nuke will no longer irradiate the surrounding area when opened

### CODE REVIEW

**Comment by Iamgoofball** [comment]
>Nuke will no longer irradiate the surrounding area when opened

No.

Fucking no.

**Comment by Rinoka** [comment]
I understand why this is suggested. Fix #10632 by making it an objective Wizards can't do or simplifying it for wizards. Explain how you fixed #10876; what are the exact steps?

It is not a good merge, because it oversimplifies an already very easy objective as long as you know the exact chain of things, akin to deconstruction/construction.

:-1:

**Comment by xxalpha** [comment]
Damned if I do, damned if I don't.

**Comment by Rinoka** [comment]
There are ways to fix this that aren't outright removing some parts of the nuke system that make sense. This is telling Wizards that all they have to do is teleport, steal a toolbox, teleport into vault, disable cameras before alarm goes up, and pop the core out. Bam, done.

Similarly, now all it takes is a single toolbox for any role - it's just that someone would need to bust into the vault by deconstructing the maint wall (which all traitors have access to; agent cards remain godlike).

The objective is already easy to get to, don't make it this easy to complete. It's fucking stupid right now, I agree with #10876. But I'd rather make the challenge of it higher than getting basic construction tools.

**Comment by Iamgoofball** [comment]
If this gets merged I'm editing my PR to re-add the radioactivity, because for fuck's sake removing it is just flat out making it too easy because a few people whined "wah wah im 2 lazy 2 use common sense and assume the nuke is radioactive when i take it apart :*("

**Comment by Steelpoint** [comment]
Correct me if I'm wrong but don't nuclear weapon core's only leak if they sustain damage? Meaning realisticly the only way for this nuke to start leaking radiation is if someone damaged the actual core.

**Comment by Dorsisdwarf** [comment]
In this case, the "core" is the actual lump of plutonium inside what is considered in normal nuclear terminology to be the core.


I don't approve of this. While to begin with the objective was poorly-thought out and clunky, literally including the wrong instructions on purpose, it's getting better, and it's the most interesting Steal objective out there.

Just make wizards unable to get it, for fuck's sake.

**Comment by Boredone** [comment]
Wasn't one of the reasons the deconstruction required a fancy Traitor screwdriver so that the crew can't take the nuke apart?

**Comment by bustygoku** [comment]
gameplay > realism

**Comment by NSSherlock** [comment]
There's no reason to remove the radiation or the special tools. #10903 resolves the primary issue with radiation: the in-game instructions not actually mentioning the need for rad gear. And removing the special tools without also removing the rads would just be asking for trouble because then *anyone* could open the core.

This could be one of the better (read: more challenging) objectives with some tweaks. Please don't just remove all of the risk. We don't need more easy steal objectives.

@Iamgoofball 
I actually made this stupid mistake, and even I don't want it removed.

If, however, you want to tone it down so that third-parties just walking past the vault through adjacent maint tunnels (on the other side of two walls, including one rwall, in the case of Meta) don't suddenly collapse straight into crit without warning because some idiot left the core exposed, then that's another story. But maybe that would require a rework of the whole rad system.

**Comment by Rinoka** [comment]
re: traitor screwdriver being to lock out crew, i understand why you wouldn't want people playing volleyball in radsuits but that would also be Fun (within reason).

Just slap an ID lock on the hatch that requires either emag or two head IDs, for those !!FUN!! rounds where you're given a task list of shit to grab and then someone spaces the stamp, like an asshole.

**Comment by NSSherlock** [comment]
@Rinoka 
It's *really* deadly. It's pretty much lethal within 30 seconds or so, even through multiple walls.

If I understand the code correctly, it's not actually possible to remove the core without the container. The purpose of the special screwdriver, then, is not to keep Joe Griefer from running around the station with the core, but rather from breaching the warhead in the first place and *permanently* irradiating the whole area (because once the core is exposed, the only way to stop the radiation is to remove the core from the warhead, which is impossible without the syndicate-issued container—there's no way to re-seal the nuke). So, essentially, it's a two-part fail-safe.

**Comment by Shadowlight213** [comment]
@xxalpha An issue that no longer neading special tools also brings up is if the crew finds the nuke in nuke ops, they can literally just decon the nuke instead of needing the code and disk to turn it off.

**Comment by Rinoka** [comment]
@NSSherlock Jesus christ. That's just silly.

There should be a ghetto but awful option for the container to be replaced - maybe a box wrapped in a radsuit or something? (Box applied to radsuit, to avoid shit like "BUT THAT WON'T FIT" errors.)

Also, I believe deconning a nuke that's active isn't possible, so if nukeops fucked up and left it on station it's their fault, innit?

**Comment by Nanotransistor** [comment]
It should leak rad only if you fucked up the steps. If done properly i don't see why it should leak.

**Comment by GunHog** [comment]
@Nanotransistor because putting everyone going past the vault flat on their face is hilarious and adds some risk to an otherwise super easy objective. Few people will stop you barring Sec if you hack open the vault, and if you are feeling lucky, you can by the AI tracking multitool, ask the AI to let you in (most will comply), and just wait for someone else to grab its attention, leaving you to loot the vault in peace.

Seriously, you are more likely to be stopped trying to enter EVA than you are the vault. Having the core blast radiation everywhere gives the entire crew a reason to stop you! Conflict shall ensue!

**Comment by Miauw62** [comment]
i like the radiation it's just a bit extreme and it should be explicitly mentioned where it starts giving off radiation.
should also give firesuits a little bit of rad resist or something like that.

**Comment by WJohn** [comment]
DNM on request.

**Comment by Razharas** [comment]
Actually concern seems to bo rad > no rad so dont bother

**Pull request closed without merging**
