### PR TITLE
Fixed not being able to bolt and unbolt operating doors.

### PR DESCRIPTION
**Pull request by xxalpha**
I apologize to all my silicon friends.

This should close an issue but I can't find it, maybe it's already closed.

### CODE REVIEW

**Comment by Cebasiz** [comment]
oh shit really

i thought this was a deliberate nerf

nice.jpg

**Comment by xxalpha** [comment]
It was deliberate, but not as a nerf. Should all work fine now.

**Comment by Cebasiz** [comment]
wat

explain

**Comment by xxalpha** [comment]
It was breaking animations before, so I "fixed" it.

**Comment by Cebasiz** [comment]
ahk thanks for un/re/fixing it again.

**Pull request merged**
