### PR TITLE
Revert "New chair sprites"

### LINKED ISSUE #7308: The Chairs look fucking disgusting and make no sense
They are just awful, especially from behind.

http://imgur.com/6tibLtx

### PR DESCRIPTION
**Pull request by hornygranny**
the rear sprite is hideous
fixes #7308

### CODE REVIEW

**Comment by WJohn** [comment]
Chairs are one of those things that have been around for eons. Maybe give it more than a day to see how people adjust to them?

**Comment by Kromgar** [comment]
John its hideous

**Comment by dannno** [comment]
merge asap fuck 1 day wait

**Comment by paprka** [comment]
OPEN BACKS ARE BAD I THOUGHT WE FUCKING AGREED ON THIS

AT LEAST USE OVERLAYS WHEN BUCKLING IF YOU'RE GOING TO DO THIS YOU LAZY SHIT

**Comment by TheVekter** [comment]
:+1:, pretty much everyone seems to hate how they look.

**Comment by WJohn** [comment]
Which is weird because, again, when I asked everyone in OOC nobody complained at all. Seriously guys I asked all the time why do you respond negatively now?

**Comment by TheVekter** [comment]
No clue, man. Wasn't there. I know if I'd seen it I would've voted against it.

**Comment by paprka** [comment]
STOP ASKING FOR FEEDBACK IN FUCKING OOC WJOHNSTON

WHY THE FUCK ARE YOU AN NIENHAUS MAINTAINERS LOL

**Comment by bgobandit** [comment]
The rear sprites are the worst. They're like fucking optical illusions where the longer you stare them the more the perspective flipflops

**Comment by Miauw62** [comment]
bugger off, paprika. OOC is probably the best place to ask.
you should probably fix the back sprites and make a new PR, WJ.

**Comment by WJohn** [comment]
Alright, I'll close up the back of the chairs instead.

**Comment by paprka** [comment]
These chairs are still less wide and hard to click on sooooo no thx

**Comment by WJohn** [comment]
I can make them bulkier too.

**Comment by paprka** [comment]
then why not just make the current sprites look better holy shit

**Comment by Lumipharon** [comment]
Please merge this, new chairs look pretty bad.

**Comment by Cheridan** [comment]
@WJohn You still working on new sprites?

**Comment by WJohn** [comment]
Not working on them right now, this can be merged. I'll try them again at another time but I want to tackle other projects first.

**Pull request merged**
