### PR TITLE
Fixes cloaks; Allows more item slots to have armor (such as shoes and gloves)

### PR DESCRIPTION
**Pull request by blobbernaut**
Cloaks now actually give the armor that they're supposed to have in the code now. Whoop woop!

I made a (far too) detailed explanation a few comments down

tl;dr

I made it so the only slots which can't have armor are the ID slot, ears, and glasses.

This means that this PR adds: belts, gloves, shoes, back, and suit storage to the list of slots which can have armor. None have it, but MASKS can have armor already, in fact, the welding gas mask used to have 10 melee armor.

### CODE REVIEW

**Comment by RemieRichards** [comment]
the PR is empty.

**Comment by blobbernaut** [comment]
Whoops, fucked this one up

**Comment by RemieRichards** [comment]
@blobbernaut can you add any other clothing item slots that would logically contain armour (shoes etc.) to the PR?

**Comment by blobbernaut** [comment]
sure

**Comment by Thunder12345** [comment]
Just allow the other 3 to be armoured too, doesn't make much sense for three arbitrary slots to NOT be able to have armour when the rest can

**Comment by RemieRichards** [comment]
@blobbernaut yes I remember the hands/feet system, it's just very weird to have a WHOLE BUNCH of items attempting to apply some kind of armour, when they never will, atleast now all it takes is adding some ```body_parts_covered``` flags (Also, not 100% sure on this, but I think in a few places FEET and HANDS actually do point to ARMS and LEGS, so this ~might~ make it partially work too)

**Comment by blobbernaut** [comment]
Yes, the body_parts_covered flag is what is checked when an item's armor is checked (except for acid, you can see what acid does right below in the file that's changed)

Want me to include glasses and ears slot for armor, Remie?

**Comment by RemieRichards** [comment]
@blobbernaut Haha, I know what ```acid_act()``` does, I wrote it lol.
For consistency's sake, yes please.

**Comment by blobbernaut** [comment]
'kay. You said realistically, so I didn't include pockets. Reason being, if any gloves (or small enough anything, really) are given armor, and they are put into a pocket, they would then still apply the armor to the hands while being in the pocket.

**Comment by RemieRichards** [comment]
@blobbernaut yeah that's true, perfect.

**Comment by blobbernaut** [comment]
I actually realized the RD's cloak was literally an inferior version of the CMO's cloak and the HOS's cloak was an inferior version of the CE's cloak. Buffed them slightly.

**Pull request merged**
