### PR TITLE
Fixes the C4 being planted on the DA.

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/7802

### CODE REVIEW

**Comment by Xhuis** [comment]
It seems easier to have the DA's object path in the blacklisted object check, but that's just me. I'm not sure if this would work, is it tested?

**Comment by xxalpha** [comment]
No it's not tested. I made a PR without testing anything.

Stop asking that shit.

**Comment by RandomMarine** [comment]
New issue report:
Wanted to blow up DA with c4. Put it inside instead.

**Comment by xxalpha** [comment]
Yeah, however that doesn't weight nearly as much as this.

**Comment by Incoming5643** [comment]
You can still blow up a C4 in a DA with judicious use of signalers even if you can't blow it the old way.

**Pull request merged**
