### PR TITLE
[HC] random cloning

### PR DESCRIPTION
**Pull request by hornygranny**
random ghosts who have opted in to being clones will be used for clones of dead players who have not opted out of being cloned

this doesn't work yet

### CODE REVIEW

**Comment by RemieRichards** [comment]
so people are going to end up in different bodies when they're cloned?
:-1: this isn't "hardcore", it's stupid.

**Comment by hornygranny** [comment]
you liked the idea last night

**Comment by RemieRichards** [comment]
@hornygranny last night I wasn't aware it was complete randomness, I thought it just increased the responsiveness of getting a clone, and added an option to decide not to be cloned.

**Comment by optimumtact** [comment]
also be of note that this is for the hardcore branch

**Comment by Ikarrus** [comment]
It would be cool to have something like this even on the main branch.

As in, players who don't want to be cloned (afk, logged out) can be filled in by other ghosts who want to get back in.

**Comment by freerealestate** [comment]
>As in, players who don't want to be cloned (afk, logged out) can be filled in by other ghosts who want to get back in.
Yeah. That. As opposed to stealing other people's bodies when they come up for cloning.

**Comment by Jalleo** [comment]
Does that mean another player can become the traitor or ling if they get cloned into that body?

**Comment by Dorsisdwarf** [comment]
I like this, it provides massive incentive not to die, because while the station will get your role back, you probbably won't be in it (Although apparently you can opt out with prefs?)

**Comment by hornygranny** [comment]
@Jalleo i have to figure out transferring bad guy roles

@Dorsisdwarf if you opt out you can't be cloned

**Comment by WJohn** [comment]
This'd incentivize people to use defibs even more than currently? I don't know if we actually want that.

**Comment by hornygranny** [comment]
doctors trying to save lives is a positive thing

**Comment by Falamazeer** [comment]
Could someone please explain what the hardcore branch is?
Because I want to say how retarded this, is, but I dunno if it's actually gonna affect me or not.

**Comment by hornygranny** [comment]
a separate branch with the aim of simultaneously increasing greatly likelihood of death while making death more undesirable. when it's stable it will be tried on sybil to see if any of the ideas are good

**Comment by Falamazeer** [comment]
Thank you for the reply, I'll reserve judgement then and we'll see how it goes, I'm interested in the results of such an experiment.

Nifty idea thumbs up or whatever.

**Comment by PKPenguin321** [comment]
yeah, sounds pretty neato :+1:

**Comment by freerealestate** [comment]
So let me make sure I've got this, this PR is for random ghosts stealing
your body when it's cloned?

**Comment by hornygranny** [comment]
@freerealestate yes, though you can opt out of being selected as a clone candidate

**Comment by Jalleo** [comment]
I think datum antag stuff might help with this hg

**Comment by Fox-McCloud** [comment]
This is one of the worst features I've ever heard suggested on TG with any level of seriousness given to it.

A random ghost suddenly taking over a body of a character they literally know nothing about that isn't them...and that they didn't play a single second of in the round as? It's stupid and is just going to generate paranoia and discontentment over how so and so made their character act (yes, I realize this happens with changelings, but that's very obvious to the players involved, post round--this won't be).

Goon is the epitome of 'HARDCORE' and even they don't have something this moronically stupid.

**Comment by Tokiko1** [comment]
Ghosts being cloned into traitor/ling bodies or traitors being recloned into new identities doesn't seem like a good idea, not even for hardcore. Even removing cloning completely seems like a better idea.

**Comment by hornygranny** [comment]
@Fox-McCloud special snowflakes are protected by the opt-out button

**Comment by Miauw62** [comment]
>implying hardcore isn't synonymous with stupid anyway
Op 21-jul.-2015 06:11 schreef "Remie Richards" <notifications@github.com>:

**Comment by Supermichael777** [comment]
make a higher tier  cloner have a higher chance of "restoring previous personality pattern". would probably be better as coming back with bad mutations (including deviant scum).

**Comment by Razharas** [comment]
@Cheridan 
Your decision

**Pull request closed without merging**
