### PR TITLE
fix derelict having station areas

### PR DESCRIPTION
**Pull request by xxalpha**

### CODE REVIEW

**Comment by Supermichael777** [comment]
MAPPING FREEZE

**Comment by KorPhaeron** [comment]
>MAPPING FREEZE

**Comment by xxalpha** [comment]
Only dunc can decide to freeze this.

**Comment by duncathan** [comment]
frozen

**Comment by KorPhaeron** [comment]
You'll have to redo this anyway, so no point in keeping it open

**Pull request closed without merging**
