### PR TITLE
Removes nuke steal objective 

### PR DESCRIPTION
**Pull request by xxalpha**
Fixes https://github.com/tgstation/-tg-station/issues/10632
Fixes https://github.com/tgstation/-tg-station/issues/10876

### CODE REVIEW

**Comment by Anonus** [comment]
This removes the entire process; I kind of liked the ability to steal it, but the objective was complete shit because you got no instructions, or, for that matter, indication you needed a radsuit.

**Comment by Cheridan** [comment]
Is this really needed? I think the objective can be neat, it's just that the way you have to go about doing it is very inconsistent with the rest of the game's interactions, and the instructions aren't clear.

**Comment by Iamgoofball** [comment]
get good 

:-1:

**Comment by GunHog** [comment]
:-1: This does not require removal, simply improvement. The steps and sprites are poor, not the objective itself. The ease of getting into the vault is that <b>no one cared</b> about it. I think that will change over time. The feature's concept is fine, simply bad execution.

**Comment by xxalpha** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
:-1: 

Fix it up so wizards can't get it and the objective itself is better designed/presented/handled.

It's a really unique objective--no need to kill it off.

**Comment by xxalpha** [comment]
It doesn't need fixing in my eyes. I mean the wizard getting it/not getting the box is a bug, but other than that it's what I wanted it to be.

**Comment by ike709** [comment]
Improve not remove. :-1:

**Comment by WJohn** [comment]
Yeah I'd much rather we just actually fix it instead of throwing it out. The idea is cool, it's just executed horribly.

**Comment by CPTANT** [comment]
removing the nuke core shouldn't need special tools. NO other objective requires special items (except exchanging documents, duh). If I want to steal the core I should be able to with just being crafty.

Also the procedure is completely inconsistent with any other machine interaction. Why the fuck do I suddenly need to draw lines before cutting wires?

**Comment by daman997** [comment]
how retarded do you have to be to assume that the PLUTONIUM core of a nuke isnt radioactive

**Comment by Anonus** [comment]
The problem is that players assume, naturally, that you can open it and just shove the core in the container without getting fucked by rads, and that's why they have the container. However, it doesn't work like that and will instantly fuck you with rads the second you weld it open.

**Comment by Iamgoofball** [comment]
just add "radioactive" to the adjectives of the nuke core in the objective, they'll go get a radsuit then, and if they don't they're fucking retarded and there is no hope for them

**Comment by CosmicScientist** [comment]
How screwed are you from the radiation? Dead screwed? Alive enough to limp to the medbay foyer before keeling over? I agree with improve instead of remove though.

**Comment by Anonus** [comment]
It literally stunlocks you and poisons you levels of dead.

**Pull request closed without merging**
