### PR TITLE
Bandanas/More jumpsuits in mixed

### PR DESCRIPTION
**Pull request by dannno**
Mainly bandanas

just some bandanas that spawn in various lockers for fun. 
I also removed an extraneous lightblue jumpsuit from the code and added more jumpsuit colors to the mixed lockers.

I plan to add more kinds of bandanas in the future when I get the sprites.

sorry for all the commit nonsense :]

### CODE REVIEW

**Comment by paprka** [comment]
Fucking NT station shill trying to turn /tg/ into NTstation

Shame on you dannos SHAME ON YOU

**Comment by TZK13** [comment]
So something I never liked about bandanas is that they're a mask even when worn on your head, I don't know how plausible it is to make it so that it converts between being a mask and a head item when you switch it but that would really be nice. Really though if it had to be one or the other I'd prefer it to be a head item so that clowns and mimes can wear them.
So something I never liked about bandanas is that they're a mask even when set to be worn on the head, I don't know how plausible it is to make it so that it converts between being a mask and a head item but that would really be nice. Really though if it had to be one or the other I'd prefer it to be a head item so that clowns and mimes can wear them.

**Comment by paprka** [comment]
@dannno  ^ look at https://github.com/tgstation/-tg-station/pull/6771/files

**Comment by tkdrg** [comment]
OR you can just make them be equippable in 2 different slots (mask & head), each with their respective sprites. Look at the katana (back/belt) or the suspenders (belt/suit) if you want to know how to do that. It makes more sense to me.

**Comment by TZK13** [comment]
That actually does seem like by far the best way to implement it.

Although you're wrong about the suspenders you can't wear those on your belt.

**Comment by dannno** [comment]
I'm gonna look into what tkrdg said, since the reason I made them asks was so that when in head-mode they could go under hats to look cool and his idea would maintain that

**Comment by tkdrg** [comment]
Huh, you're right, they can't. I wonder why I thought otherwise. Anyway, katanas (back/belt), pens (ears/belt) and PDAs (belt/ID) can be worn in more than one slot.

**Comment by TZK13** [comment]
Huh, I had no idea you could put a pen on your ear slot.

**Comment by spheretech** [comment]
These are great, far better than my half arsed ones.

**Comment by tkdrg** [comment]
Merge conflicts

**Comment by dannno** [comment]
auugghgh i dont remember how to fix these

**Comment by pudl** [comment]
can you remove my skull bandana? i personally am ashamed of the sprite

**Comment by dannno** [comment]
no

**Comment by pudl** [comment]
:(

**Comment by paprka** [comment]
give the skull bandana a low chance to spawn in robotics lockers for maximum cool points

**Comment by dannno** [comment]
gonna close and make a new one because i don't remember shit about conflicts

**Pull request closed without merging**
