### PR TITLE
adds more barsigns

### PR DESCRIPTION
**Pull request by dannno**
view raw for animations, cba to make gifs

### CODE REVIEW

**Comment by Niknakflak** [comment]
All great but im unsure of what "The old cock inn" is supposed to mean.  Sprite looks good though.

**Comment by Miauw62** [comment]
combo cafe is great

**Comment by Atskadan** [comment]
>im unsure of what "The old cock inn" is supposed to mean

nobody tell him

**Comment by TZK13** [comment]
>All great but im unsure of what "The old cock inn" is supposed to mean.
>Being this out of the loop.

**Comment by Jordie0608** [comment]
Changelog

**Comment by Chocobro** [comment]
vlad's salad is a very nice one. wordplay and a shiny sprite? love it.

**Comment by dannno** [comment]
changes logged

**Pull request merged**
