### PR TITLE
Fixes still being able to use jetpacks as internals.

### PR DESCRIPTION
**Pull request by xxalpha**

### CODE REVIEW

**Comment by Steelpoint** [comment]
I thought that was a feature?

**Comment by TZK13** [comment]
No, it was just an unforeseen consequence of changing paths from what I can gather.

**Comment by PKPenguin321** [comment]
I figured this was intended. Why remove it if it still functions, excluding the HuD icon for internals? There's no reason from what I can tell.

**Comment by TZK13** [comment]
It's a pain in the ass as a nukeop to have to actually have their oxygen tank on their person when they're using the jetpack, what's even the point of oxygen jetpacks if you can't use them as internals? All jetpacks may as well be carbon dioxide ones then.

**Comment by xxalpha** [comment]
You keep your jetpack equipped as a nuke op the entire time?

**Comment by TZK13** [comment]
Obviously not, when you get on station and take it off though you'll also want to take off your oxygen tank, most likely to be put back in your internals box. Then when you're about to go back into space you'll have to take your internals box out, grab the oxygen tank, and place it on your person again. Nukeops have a LOT of shit to carry around so this is just obnoxious inventory management at critical points.

**Comment by xxalpha** [comment]
Why would you ever stop using internals as nuke ops?

**Comment by Lumipharon** [comment]
Because you need the inventory space...
Literally the whole point of the oxygen jetpacks (ops, NASA and captain's jetpack) is to save inventory space by having the jetpack double as internals. It's why they exist, it is a feature.

Also related, dunno if it effects the others, but with the captain's jetpack now, you have to manually turn on the internals mask valve thing, instead of being able to just press the normal internals button, which is retarded as fuck.

**Comment by xxalpha** [comment]
The previous change was supposed to remove the ability to breathe with jetpack, but I'll restore it if that's what you want.

**Comment by paprka** [comment]
This is a really bad change. https://github.com/tgstation/-tg-station/pull/7914 does it better. Don't remove features xxalpha. The reason jetpacks use breathable gas like o2 is specifically so they can double as jetpacks.

**Comment by xxalpha** [comment]
Looks like it's taken care of.

**Pull request closed without merging**
