### PR TITLE
changes handheld radio sprite to be cooler

### PR DESCRIPTION
**Pull request by dannno**
walterje's sprite is better than the one we have now so

### CODE REVIEW

**Comment by WJohn** [comment]
I personally like the big green walkie-talkie we have for a handheld radio... This looks too much like the multitool for me, personally.

**Comment by ike709** [comment]
walkie talkies!

**Comment by Fox-McCloud** [comment]
I'd suggest making it green with a blue screen, just so people recognize it as "hey, this is the same thing".

In any event, I do like the smaller size, but I definitely agree with WJohn taht it has too much overlap with the multitool.

**Comment by Miauw62** [comment]
I like the current sprite better, TBH. this looks too much like the
signaller and the multitool.

**Comment by paprka** [comment]
I like the old fashioned big and bulky radio

**Comment by dannno** [comment]
?

**Comment by WJohn** [comment]
Now that's entirely too similar to our remote signaler.

I'd be happy to see the yellow one be used for the multitool, though.

**Comment by Lumipharon** [comment]
Our current radio is a lovely green brick, which looks fine to me.

**Comment by Fox-McCloud** [comment]
Really like that, but yeah, it's a bit too similar now =/

Most common walkie talkie colors: Black, yellow, orange, and blue....so your first yellow color wasn't too far off from that---I really like the green, but yeah...overlap.

**Comment by dannno** [comment]
??

**Comment by Fox-McCloud** [comment]
Ohhh, that's very nice, in my opinion.

**Comment by pudl** [comment]
yellow makes the most sense, but honestly handheld radios are so rarely used there's little to no point in respriting them

**Comment by Deantwo** [comment]
I am the only one that always carry a radio just in case?
And I got to use it like ever 3rd round or so.

But yeah I like the current one better too.
Yellow one looks like multitool or signaller, and the red one looks like a bomb or something.

**Comment by Razharas** [comment]
Is it me or sprites look like they have a skull on them?
Pirate radios

**Pull request closed without merging**
