### PR TITLE
fixes dufflebag max weight class

### PR DESCRIPTION
**Pull request by dannno**
Fixes https://github.com/tgstation/-tg-station/issues/7432

### CODE REVIEW

**Comment by dannno** [comment]
the simplest thing ever if you wanted to merge it right away :-)

**Comment by RemieRichards** [comment]
it can be merged the moment it says "24 hours ago"

**Comment by Deantwo** [comment]
> it can be merged the moment it says "24 hours ago"

I don't think GitHub ever says that. Pretty sure it says "a day ago".

**Comment by dannno** [comment]
REMIE IS STACKING THIS AGAINST ME
FUCKING MAINTAINERS GRUDGING ME
REBEL
NTSTATION 2.0
:gun:

**Comment by RemieRichards** [comment]
@Deantwo Haha that's right! Wow ok, I guess this can <i>never be merged</i> :3

**Comment by dannno** [comment]
merge

**Comment by Deantwo** [comment]
var/timestamp = "2 days ago"
if(timestamp == "24 hours ago") PR.Merge

**Pull request merged**
