### PR TITLE
removes lesser summon guns

### LINKED ISSUE #15294: Lesser Summon Guns + Lich is OVERPOWERED
OVERPOWERED COMBINATION AS BAD AS MAGIC MISSILE + DISINTERGRATE!
Either remove either of the spells, or make that particular combination unbuyable because what the fuck man LSG gives you the most stopping power in the game. The guns do more damage then a pulse rifle, their bullets are almost invisible, AND ITS INFINITE. With lich you can kill the entire crew without anyone being able to stop you because anyone able to stop you will be dead. Or, lower the damage of the damned bolt action enchanted rifles.

### PR DESCRIPTION
**Pull request by hornygranny**
i can't take another round of watching the wizard click on people until they die. it's not flavorful, it doesn't require creative play, it's not fun for the victims or even different than other antags. we deserve better than this. make wizard great again

Fixes #15294 
Closes #15303

### CODE REVIEW

**Comment by lzimann** [comment]
ayy

**Comment by feemjmeem** [comment]
meme :-1:

**Comment by PKPenguin321** [comment]
>when the features are too much fun

**Comment by MrPerson** [comment]
THEY'RE TAKING MUH GUNS AWAY :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us:

**Comment by Hatfish** [comment]
Where's the i ded tag?

**Comment by Buggy123** [comment]
:8ball:

**Comment by ExcessiveUseOfCobblestone** [comment]
# yes

**Comment by WJohn** [comment]
In this case I agree that lesser summon guns is entirely too powerful. It's basically better than ei nath because it's ranged, you can kill multiple people with it, and you don't even have to aim or click on anyone in particular to do it with. It's basically way better than mutate.

**Comment by optimumtact** [comment]
Maximum I ded pls nerf

**Comment by freerealestate** [comment]
anything that makes the game play less like call of duty

**Comment by JJRcop** [comment]
leave the spell, take it out of the book?

**Comment by feemjmeem** [comment]
If wizards don't murderbone, people think they're shit. If wizards do murderbone, people think they're shit.

If wizards murderbone too well, it's because the spells are too strong. If they don't murderbone enough, it's because they need more spells.

What do you actually want wizards to be?

**Comment by freerealestate** [comment]
Characters who give the players gameplay opportunities through natural roleplay

**Comment by Fox-McCloud** [comment]
why not try nerfing it first, before removing it.

You know, longer cooldown, less guns, increased spell cost, different bullets?

This spell has a LOT of levers that can be pulled or adjusted to adjust how strong it is--out and out removal when it can be tweaked (extensively) seems reactionary and, no offense, stupid.

With spells like Ei Nath? I can understand wanting to remove spells like *that* (I'm not suggesting removing Ei Nath), as there's not many levers to tinker with, but this is not that kind of spell.

**Comment by hornygranny** [comment]
https://github.com/tgstation/-tg-station/pull/14146

**Comment by Zilenan91** [comment]
So is this happening anytime soon? LSG is honestly way too good for what it does since it gives the wizard an undroppable machine gun.

**Comment by kevinz000** [comment]
Alternatively give it a lower cooldown like 10-20 wizard spell cooldown ticks or whatever the numbers mean
AND
Make it only give you ONE gun
So occasionally the wizard can shoot you wit ha LMG damage bullet
But he can't spam this shit forever

**Comment by YakumoChen** [comment]
I'm pretty sure the whole point of LSG was it was a refrence to Madoka, so removing all but one gun ruins the reference.

Just change the damage or the cooldown. It's been done before, it can be done again.

@KorPhaeron because it's his spell in the first place

**Comment by ExcessiveUseOfCobblestone** [comment]
Another option would be to give the gun a second bullet so feel free to click-spam, but each click gives the crew an opportunity to wreck you as well.

**Comment by Zilenan91** [comment]
Just make the crew able to make ammo for these fucking things so it's not a better LMG.


Or we could just remove it and be done with this shit that even Kor knows is OP.

**Comment by KorPhaeron** [comment]
@YakumoChen 

Don't care enough to argue about it forever. Making it do less damage or whatever would make more sense than removal though, since the game has functioned fine for several years with mutate (laser eyes+hulk).

**Comment by duncathan** [comment]
Kor made his own pr so I'll close this one

**Pull request closed without merging**
