### PR TITLE
only wizards and cultists can use soul shards

### PR DESCRIPTION
**Pull request by hornygranny**
flavor messages check for wizard or cultist creator
var usability will allow for anybody to use one

### CODE REVIEW

**Comment by Ergovisavi** [comment]
>user.Dizzy(120)

120 ticks of dizziness? I mean, it's arcane evil wackiness, sure. But yikes.

Also, guess these need to be removed from the mining vaults, then.

**Comment by Jordie0608** [comment]
:+1: An annoying thing in cult rounds.

**Comment by Ergovisavi** [comment]
This needs to adjusted for DE/REconverts. If your master gets deconverted from the cult, we're just in a similar situation, etc.

**Comment by dannno** [comment]
Make chaplain able to use them as well, some maps allow chaplain to spawn with one. It makes sense too.

**Comment by Steelpoint** [comment]
There was a idea on IRC to make some unique sprites and changes.

If a non-cultist makes a construct, that construct uses a blue sprite, cannot see who is a cultist and is not tied to anyone.

If a Wizard makes a construct, that construct gets a purple sprite.

**Comment by Miauw62** [comment]
Because non-cultists making non-cultist constructs worked so well in the
past. Just have an antagonly var that's enabled on wizard and cult shards
but disabled on spawned and mining shards. Bam, problem solved while not
fucking over admins wanting to use shards.
Op 8-jan.-2015 13:44 schreef "Steelpoint" <notifications@github.com>:

**Comment by dannno** [comment]
That works far better.

**Comment by TZK13** [comment]
I like Miauw's idea far more than this.

**Comment by S0ldi3rKr4s0** [comment]
>and then people proceed to meta what gamemode it is using shards from mining

gr8 solution guys I r8 it 8/8

**Comment by TZK13** [comment]
How would that even work, I don't think that implementation means what you think it means.

**Comment by dannno** [comment]
kraso is just doing what he does
be a retard

**Comment by TZK13** [comment]
Like the idea isn't that all shards within a round are one way or the other so a shat miner couldn't just realize they can't use it and meta the gamemode based on that. You also can't really use it as an antag test because if you have a shard that anybody can use then... anybody can use it? And how would you feasibly get your hands on a shard from a cultist or wizard without being able to tell the gamemode by doing so?

**Comment by ACCount12** [comment]
No. Cult that manages to lose soul stone shard AND construct shell deserves being killed by constructs. Same for wizard.

**Comment by Lumipharon** [comment]
Constructs aren't cult if there master isn't anymore, why is this even needed?

**Comment by as334** [comment]
Because they can still see who is and isn't cultists.

**Comment by TZK13** [comment]
What, no they don't. Last time I was a security construct I sure as shit wasn't able to see cultist icons above people's heads.

**Comment by Lumipharon** [comment]
I have literally tested this ingame. if YOU are not a cultist, your SHADES and CONSTRUCTS are not, and cannot see who is. This was fixed months ago afaik.

**Comment by as334** [comment]
Really? Because i've been busted as a cultist by non-cult constructs just a couple weeks ago.

**Comment by TZK13** [comment]
Maybe they were cultists before they were constructed and knew you were a cultist?

**Comment by Boggart** [comment]
I think that the last time this came up someone said that rune created shards may be cultists while ones from sharding a corpse aren't, not postive on that though.

**Comment by Boggart** [comment]
#6922 fixes this without removing the ability for non-antags to use the stones.

**Comment by AnonymousNow** [comment]
I have to object to this. The flexibility of soul shards is too good a thing to sacrifice, and it should feel like a weapon that can be recovered and turned against the tide. At the least - at the very, very least - allow the chaplain to use them, just like he did when a shard spawned on his table.

**Comment by MrPerson** [comment]
:+1: A better solution. Keeps the gamemode more focused.

This is like the fourth time we've solved this exact problem. I'm tired of it.

**Comment by Miauw62** [comment]
seriously though @hornygranny add a var to soulstones so they're not completely limited to cult/wizard rounds, they're fun for admin events and the mining shard is pretty cool too.

**Comment by Miauw62** [comment]
very good. :+1:

**Pull request merged**
