### PR TITLE
Grayscale Lighters

### PR DESCRIPTION
**Pull request by xxalpha**
Original lighters
base_lighters

Grayscale lighters (there are more colors than this but byond rng)
new_lighters
----
Updated colors:
lighters_cyanscale

-------------------------------
update: no zippos in this PR

### CODE REVIEW

**Comment by JJRcop** [comment]
Those zippos actually look slick.

**Comment by dannno** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: we need to greyscale shit like screwdrivers and cable coils too

**Comment by dannno** [comment]
or like, everything really

**Comment by Incoming5643** [comment]
Something survive greyscaling better than others, but this one works really well :+1:

**Comment by xxalpha** [comment]
The trick was not painting the lighters in shades of gray. :speedboat:

**Comment by Nienhaus** [comment]
No more red lighters :c
Orange and pinkish orange lighters 2015

**Comment by Incoming5643** [comment]
Pastel lighters are the future

**Comment by xxalpha** [comment]
One of them is reddish!

**Comment by Lumipharon** [comment]
The zippo's aren't bad, put personally I prefer the plain metal finish, with a logo on it.
Hell, why not both?

**Comment by xxalpha** [comment]
Like this, lumi?
zippos2
zippos3

Syndie one doesn't look so good, but I might keep the blue NT logo on metal one.

**Comment by dannno** [comment]
The ones in the OP look completely fine. Leave them like that.

**Comment by Nienhaus** [comment]
@xxalpha That's more pinkish orange

**Comment by xxalpha** [comment]
One more.
syndiezippo

**Comment by Jordie0608** [comment]
For the random colors, couldn't you just use (rgb(rand))?

**Comment by xxalpha** [comment]
You risk getting some that look like ass, also grays.

**Comment by Jordie0608** [comment]
Byond has web colors inbuilt and I think you can use them with RGB or color vars, but it's possible they may only work with text.

Also changelog.

**Comment by Lumipharon** [comment]
The one with just the blue N looks good. Your 3rd synde one is also pretty neat. Ideally it would just like, real life engraving on the side, but that would probably look shit in this.

**Comment by Cheridan** [comment]
Can you really call it grayscaling if the color you use isn't gray at all?? :thought_balloon:

**Comment by Fox-McCloud** [comment]
:+1: on the "greyscaling"

:-1: on the switch

If we go by the main primarily recognized: Black, white, red, orange, yellow, green, blue, violent we have 8 colors; I'd only make 8 more that were between these so there's a smoother array of colors available rather than strongly favoring the more pastel colors.

**Comment by xxalpha** [comment]
Sample of colors from an overlay in grayscale and not cyanscale.

lighters_grayscale

**Comment by xxalpha** [comment]
New color list samples:
Grayscale
lighters_grayscale

Cyanscale
lighters_cyanscale

**Comment by dannno** [comment]
the ones in the the op look much brighter? what happened

**Comment by xxalpha** [comment]
Likely the rendering. I am on a new machine.

**Comment by Dorsisdwarf** [comment]
How did you make only the body greyscaled?

**Comment by xxalpha** [comment]
It's an overlay. Look at the New proc.

**Comment by MrStonedOne** [comment]
space station 13 2015-03-01 130354

**Comment by xxalpha** [comment]
I actually have a slightly different list of colors, haven't updated yet.

**Comment by Miauw62** [comment]
The new zippos look sort of shitty imo, I prefer the light grey ones with a
logo.

**Comment by xxalpha** [comment]
I removed them for a new PR.

**Pull request merged**
