### PR TITLE
renames beach love shack to comply with lore

### PR DESCRIPTION
**Pull request by hornygranny**

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
YES

**Comment by KorPhaeron** [comment]
oh my god

**Comment by TechnoAlchemisto** [comment]
+!!!!!!!111111111111111111111111111111111111111111111111111111

**Comment by TechnoAlchemisto** [comment]
never 4get the cuckshed

**Comment by Buggy123** [comment]
something something separation codebase something players

:+1:

**Comment by PKPenguin321** [comment]
mekhi being a cuck is now canon

**Comment by KazeEspada** [comment]
This is the kind of shit that makes me dislike @hornygranny

**Comment by optimumtact** [comment]
current player reference and therefore illegal

**Comment by Impisi** [comment]
Then remove the Cuba Pete hat.

**Comment by xxalpha** [comment]
If you want to make this reference you need to permaban the person first so it is not a player reference.

**Comment by SweaterKittens** [comment]
10/10

**Comment by Zilenan91** [comment]
This is fucking funny lmao

**Comment by Shapsy** [comment]
My legacy is dead and it feels so good

**Comment by Aloraydrel** [comment]
AYYY

**Comment by PKPenguin321** [comment]
IT GOT MERGED PogChamp

**Comment by kevinz000** [comment]
wait what

**Pull request merged**
